"""
Django settings for jstocks project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 기본값을 두지 않는다 — .env 를 못 읽으면 조용히 취약해지는 대신 즉시 실행이 실패하도록.
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())

# HTTP 환경에서 COOP 헤더 경고 비활성화
SECURE_CROSS_ORIGIN_OPENER_POLICY = None


# === nginx 뒤에서 돌 때 ===
#
# 전부 .env 로 가른다. TLS 를 켜기 전에 코드만 올려도 아무것도 달라지지 않고,
# 인증서가 붙은 뒤 .env 를 고쳐 켜면 된다. 반대로 하면 — 쿠키를 먼저 https
# 전용으로 바꾸면 — 그 순간 로그인이 안 된다.

# nginx 가 X-Forwarded-Proto 를 넘긴다. 이것이 없으면 Django 는 https 요청을
# http 로 알고, 리다이렉트 주소와 CSRF 판정이 어긋난다.
if config('BEHIND_TLS_PROXY', default=False, cast=bool):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Django 4 부터 POST 는 Origin 과 이 목록을 맞춘다. 스킴까지 적어야 한다.
#   CSRF_TRUSTED_ORIGINS=https://example.com
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

# 쿠키를 https 에서만 보낸다. 인증서가 실제로 뜬 뒤에 켠다.
SESSION_COOKIE_SECURE = config('SECURE_COOKIES', default=False, cast=bool)
CSRF_COOKIE_SECURE = SESSION_COOKIE_SECURE

# http -> https 는 nginx 가 돌린다. 여기서 또 하면 리다이렉트가 두 번 돈다.
SECURE_SSL_REDIRECT = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'axes',   # 로그인 시도 제한
    'stocks',
    'ontoo',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'stocks.middleware.LoginRequiredMiddleware',
    # axes 는 맨 뒤여야 한다 (패키지 문서의 요구).
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'jstocks.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jstocks.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
#
# axes 백엔드가 먼저 와야 로그인 시도를 세고 잠긴 주소를 막는다. ModelBackend
# 는 그대로 남겨 둔다 — 실제 인증은 그쪽이 한다.
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# === 로그인 시도 제한 (django-axes) ===
#
# /login/ 과 /admin/login/ 에 무제한으로 시도할 수 있었다. 들어오는 문이 둘뿐인
# 자리라 이것만 막아도 크게 줄어든다.
AXES_FAILURE_LIMIT = config('AXES_FAILURE_LIMIT', default=10, cast=int)

# 주소로 센다. 아이디로 세면 공격자가 내 아이디를 열 번 틀려 나를 잠글 수 있다
# — 쓰는 사람이 나뿐이라 그쪽이 더 나쁘다.
AXES_LOCKOUT_PARAMETERS = ['ip_address']

# 한 시간 뒤 저절로 풀린다. 영구 잠금은 내가 오타를 냈을 때도 영구다.
AXES_COOLOFF_TIME = config('AXES_COOLOFF_HOURS', default=1, cast=int)

# 한 번 성공하면 지금까지의 실패를 지운다.
AXES_RESET_ON_SUCCESS = True

# 잠겼을 때 뜨는 말. 나머지 화면이 한국어라 맞춘다.
AXES_COOLOFF_MESSAGE = (
    f'로그인 시도가 너무 많습니다. '
    f'{config("AXES_COOLOFF_HOURS", default=1, cast=int)}시간 뒤에 다시 시도하세요.'
)

# 진짜 접속자 IP 를 읽는 법.
#
# nginx 뒤라 REMOTE_ADDR 은 전부 127.0.0.1 이다. 기본값(REMOTE_ADDR)을 그대로
# 두면 한 사람이 열 번 틀렸을 때 모두가 잠긴다. 자세한 이유는 그 함수에 적었다.
AXES_CLIENT_IP_CALLABLE = 'stocks.middleware.client_ip'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'login'
