from django.urls import path
from . import views

app_name = 'stocks'

urlpatterns = [
    path('', views.index, name='index'),
    path('stocks/', views.stock_list, name='stock_list'),
    path('stocks/<str:code>/', views.stock_detail, name='stock_detail'),
    path('stocks/<str:code>/edit/', views.stock_edit, name='stock_edit'),
    path('api/stock/<str:code>/memo/', views.stock_memo_save, name='stock_memo_save'),
    # 자료 (뉴스·유튜브 등 다시 읽을 링크와 그 요약)
    path('api/stock/<str:code>/material/', views.material_save, name='material_save'),
    path('api/material/<int:material_id>/update/', views.material_update, name='material_update'),
    path('api/material/<int:material_id>/delete/', views.material_delete, name='material_delete'),
    path('api/stock/<str:code>/supply-demand-analysis/', views.stock_supply_demand_analysis_save, name='stock_supply_demand_analysis_save'),
    path('api/stock/<str:code>/financial-analysis-v2/', views.financial_analysis_v2_save, name='financial_analysis_v2_save'),
    path('api/stock/<str:code>/consensus-analysis/', views.consensus_analysis_save, name='consensus_analysis_save'),
    path('api/stock/<str:code>/income-statement/', views.income_statement_list, name='income_statement_list'),
    path('api/stock/<str:code>/income-statement/save/', views.income_statement_save, name='income_statement_save'),
    path('api/stock/<str:code>/balance-sheet/', views.balance_sheet_list, name='balance_sheet_list'),
    path('api/stock/<str:code>/balance-sheet/save/', views.balance_sheet_save, name='balance_sheet_save'),
    path('api/stock/<str:code>/cash-flow/', views.cash_flow_list, name='cash_flow_list'),
    path('api/stock/<str:code>/cash-flow/save/', views.cash_flow_save, name='cash_flow_save'),
    path('api/stock/<str:code>/stability/', views.stability_list, name='stability_list'),
    path('api/stock/<str:code>/stability/save/', views.stability_save, name='stability_save'),
    path('api/stock/<str:code>/consensus/', views.consensus_list, name='consensus_list'),
    path('api/stock/<str:code>/growth/', views.growth_list, name='growth_list'),
    path('api/stock/<str:code>/growth/save/', views.growth_save, name='growth_save'),
    path('api/stock/<str:code>/profitability/', views.profitability_list, name='profitability_list'),
    path('api/stock/<str:code>/profitability/save/', views.profitability_save, name='profitability_save'),
    path('stocks/<str:code>/insight/summary/', views.stock_insight_summary_html, name='stock_insight_summary_html'),
    path('stocks/<str:code>/insight/report/', views.stock_insight_report_html, name='stock_insight_report_html'),
    path('api/stock/<str:code>/signal-chart/', views.signal_chart_data, name='signal_chart_data'),
    path('asset/', views.asset, name='asset'),
    path('market/', views.market, name='market'),
    path('etf/<str:code>/', views.etf_detail, name='etf_detail'),
    path('api/etf/add/', views.add_etf, name='add_etf'),
    path('api/etf/save/', views.save_etf, name='save_etf'),
    path('api/etf/<str:code>/delete/', views.delete_etf, name='delete_etf'),
    path('api/etf/<str:code>/signal-chart/', views.etf_signal_chart_data, name='etf_signal_chart_data'),
    # ETF 메모
    path('api/etf/<str:code>/memo/', views.etf_memo_save, name='etf_memo_save'),
    path('api/stock/search/', views.search_stock, name='search_stock'),
    path('api/stock/<str:code>/prompt-data/', views.fetch_stock_prompt_data, name='fetch_stock_prompt_data'),
    path('api/stock/<str:code>/data-loader/', views.fetch_stock_data_loader, name='fetch_stock_data_loader'),
    path('api/stock/<str:code>/data-loader-with-summary/', views.fetch_stock_data_loader_with_summary, name='fetch_stock_data_loader_with_summary'),
    # 투자일기
    path('api/diary/', views.diary_list, name='diary_list'),
    path('api/diary/save/', views.diary_save, name='diary_save'),
    path('api/diary/<int:diary_id>/update/', views.diary_update, name='diary_update'),
    path('api/diary/<int:diary_id>/delete/', views.diary_delete, name='diary_delete'),
    # 종목별 투자일지
    # 종목별 이벤트
    path('api/dart-document/<str:rcept_no>/', views.fetch_dart_document, name='fetch_dart_document'),
    path('api/business-report/<str:code>/', views.fetch_business_report, name='fetch_business_report'),
    path('settings/', views.settings, name='settings'),
    path('api/category/add/', views.category_add, name='category_add'),
    path('api/category/<int:category_id>/delete/', views.category_delete, name='category_delete'),
    path('api/theme/add/', views.theme_add, name='theme_add'),
    path('api/theme/<int:theme_id>/delete/', views.theme_delete, name='theme_delete'),
    path('api/theme/resolve/', views.theme_resolve, name='theme_resolve'),
    # 애널리스트 리포트
    path('api/report/<int:report_id>/file/delete/', views.report_file_delete, name='report_file_delete'),
    # 텔레그램 (종목)
    path('telegram/<int:message_id>/summary/', views.telegram_summary, name='telegram_summary'),
    path('api/telegram/message/save/', views.telegram_message_save, name='telegram_message_save'),
    path('api/telegram/message/<int:message_id>/delete/', views.telegram_message_delete, name='telegram_message_delete'),
    # 질문리포트 (종목)
    path('research/<int:report_id>/', views.stock_question_report_detail, name='stock_question_report_detail'),
    path('research/slot/<str:code>/', views.stock_question_report_slot, name='stock_question_report_slot'),
    path('api/stock/question-report/save/', views.stock_question_report_save, name='stock_question_report_save'),
    path('api/stock/question-report/<int:report_id>/update/', views.stock_question_report_update, name='stock_question_report_update'),
    path('api/stock/question-report/<int:report_id>/delete/', views.stock_question_report_delete, name='stock_question_report_delete'),
    path('api/setting/get/', views.get_setting, name='get_setting'),
    path('api/setting/save/', views.save_setting, name='save_setting'),
    # 시장 AI 판단
    # AI 판단 (시황·리포트·수급·공시가 같이 쓴다)
    path('api/ai-note/parse/', views.ai_note_parse, name='ai_note_parse'),
    path('api/ai-note/save/', views.ai_note_save, name='ai_note_save'),
    # 리서치 프롬프트
    path('api/research-prompt/', views.research_prompt_list, name='research_prompt_list'),
    path('api/research-prompt/add/', views.research_prompt_add, name='research_prompt_add'),
    path('api/research-prompt/<int:prompt_id>/update/', views.research_prompt_update, name='research_prompt_update'),
    path('api/research-prompt/<int:prompt_id>/delete/', views.research_prompt_delete, name='research_prompt_delete'),
    path('api/quick-report/', views.quick_report_list, name='quick_report_list'),
    path('api/quick-report/add/', views.quick_report_add, name='quick_report_add'),
    path('api/quick-report/<int:prompt_id>/update/', views.quick_report_update, name='quick_report_update'),
    path('api/quick-report/<int:prompt_id>/delete/', views.quick_report_delete, name='quick_report_delete'),
    path('api/summary-report/', views.summary_report_list, name='summary_report_list'),
    path('api/summary-report/add/', views.summary_report_add, name='summary_report_add'),
    path('api/summary-report/<int:prompt_id>/update/', views.summary_report_update, name='summary_report_update'),
    path('api/summary-report/<int:prompt_id>/delete/', views.summary_report_delete, name='summary_report_delete'),
    # 파일 업로드 리포트 (종목)
    path('uploaded-report/<int:report_id>/summary/', views.uploaded_report_summary_page, name='uploaded_report_summary_page'),
    path('api/stock/uploaded-report/upload/', views.stock_uploaded_report_upload, name='stock_uploaded_report_upload'),
    path('api/stock/uploaded-report/<int:report_id>/delete/', views.stock_uploaded_report_delete, name='stock_uploaded_report_delete'),
    path('api/stock/uploaded-report/<int:report_id>/summary/', views.stock_uploaded_report_summary, name='stock_uploaded_report_summary'),
    path('api/stock/uploaded-report/<int:report_id>/title/', views.stock_uploaded_report_title, name='stock_uploaded_report_title'),
]
