from django.urls import path
from . import views

app_name = 'stocks'

urlpatterns = [
    path('', views.index, name='index'),
    path('stocks/', views.stock_list, name='stock_list'),
    path('stocks/<str:code>/', views.stock_detail, name='stock_detail'),
    path('stocks/<str:code>/edit/', views.stock_edit, name='stock_edit'),
    path('market/', views.market, name='market'),
    path('sector/', views.sector, name='sector'),
    path('etf/', views.etf, name='etf'),
    path('etf/<str:code>/', views.etf_detail, name='etf_detail'),
    path('api/etf/add/', views.add_etf, name='add_etf'),
    path('api/etf/save/', views.save_etf, name='save_etf'),
    path('api/etf/<str:code>/delete/', views.delete_etf, name='delete_etf'),
    path('nodaji/<int:nodaji_id>/summary/', views.nodaji_summary, name='nodaji_summary'),
    path('youtube/<int:video_id>/summary/', views.youtube_summary, name='youtube_summary'),
    path('api/telegram/search/', views.search_telegram, name='search_telegram'),
    path('api/disclosure/search/', views.search_disclosure, name='search_disclosure'),
    path('api/report/search/', views.search_report, name='search_report'),
    path('api/nodaji/search/', views.search_nodaji, name='search_nodaji'),
    path('api/nodaji/brief/', views.fetch_nodaji_brief, name='fetch_nodaji_brief'),
    path('api/dart/<str:code>/', views.fetch_dart, name='fetch_dart'),
    path('api/schedule/<str:code>/add/', views.schedule_add, name='schedule_add'),
    path('api/schedule/<int:schedule_id>/delete/', views.schedule_delete, name='schedule_delete'),
    path('api/sector/date/', views.sector_date_data, name='sector_date_data'),
    path('settings/', views.settings, name='settings'),
    path('api/category/add/', views.category_add, name='category_add'),
    path('api/category/<int:category_id>/delete/', views.category_delete, name='category_delete'),
    path('api/theme/add/', views.theme_add, name='theme_add'),
    path('api/theme/<int:theme_id>/delete/', views.theme_delete, name='theme_delete'),
    path('api/news/search/', views.search_google_news, name='search_google_news'),
    path('api/youtube/search/', views.search_youtube, name='search_youtube'),
    path('api/youtube/search/preferred/', views.search_youtube_preferred, name='search_youtube_preferred'),
    path('api/youtube/channel/add/', views.youtube_channel_add, name='youtube_channel_add'),
    path('api/youtube/channel/<int:channel_id>/delete/', views.youtube_channel_delete, name='youtube_channel_delete'),
    path('api/youtube/preferred/add/', views.preferred_channel_add, name='preferred_channel_add'),
    path('api/youtube/preferred/<int:channel_id>/delete/', views.preferred_channel_delete, name='preferred_channel_delete'),
    path('api/youtube/video/save/', views.youtube_video_save, name='youtube_video_save'),
    path('api/youtube/video/<int:video_id>/delete/', views.youtube_video_delete, name='youtube_video_delete'),
    path('api/market/trend/<str:market>/refresh/', views.refresh_market_trend, name='refresh_market_trend'),
    path('api/sector/<str:market>/refresh/', views.refresh_sector, name='refresh_sector'),
    path('api/stock/<str:code>/refresh/', views.refresh_stock, name='refresh_stock'),
    path('api/stock/<str:code>/investor-trend/', views.fetch_investor_trend, name='fetch_investor_trend'),
    path('api/stock/<str:code>/short-selling/', views.fetch_short_selling, name='fetch_short_selling'),
    path('api/setting/save/', views.save_setting, name='save_setting'),
]
