# Generated by Django 5.2.8 on 2025-11-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='종목코드')),
                ('name', models.CharField(max_length=100, verbose_name='종목명')),
                ('market', models.CharField(choices=[('KOSPI', 'KOSPI'), ('KOSDAQ', 'KOSDAQ'), ('KONEX', 'KONEX')], max_length=10, verbose_name='시장구분')),
                ('market_cap', models.BigIntegerField(blank=True, null=True, verbose_name='시가총액')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '종목정보',
                'verbose_name_plural': '종목정보',
                'db_table': 'info',
                'ordering': ['code'],
            },
        ),
    ]
