# Generated by Django 5.2.8 on 2025-11-29 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='거래일자 (YYYYMMDD)', verbose_name='일자')),
                ('individual', models.BigIntegerField(help_text='개인투자자 순매수량 (API: ind_invsr) - 양수: 순매수, 음수: 순매도', verbose_name='개인 순매수')),
                ('foreign', models.BigIntegerField(help_text='외국인투자자 순매수량 (API: frgnr_invsr) - 양수: 순매수, 음수: 순매도', verbose_name='외국인 순매수')),
                ('institution', models.BigIntegerField(help_text='기관계 전체 순매수량 (API: orgn) - 양수: 순매수, 음수: 순매도', verbose_name='기관 순매수')),
                ('domestic_foreign', models.BigIntegerField(help_text='내외국인 순매수량 (API: natfor) - 양수: 순매수, 음수: 순매도', verbose_name='내외국인 순매수')),
                ('financial', models.BigIntegerField(blank=True, help_text='금융투자 순매수량 (API: fnnc_invt) - 증권사 등', null=True, verbose_name='금융투자 순매수')),
                ('insurance', models.BigIntegerField(blank=True, help_text='보험 순매수량 (API: insrnc)', null=True, verbose_name='보험 순매수')),
                ('investment_trust', models.BigIntegerField(blank=True, help_text='투신(투자신탁) 순매수량 (API: invtrt)', null=True, verbose_name='투신 순매수')),
                ('other_finance', models.BigIntegerField(blank=True, help_text='기타금융 순매수량 (API: etc_fnnc)', null=True, verbose_name='기타금융 순매수')),
                ('bank', models.BigIntegerField(blank=True, help_text='은행 순매수량 (API: bank)', null=True, verbose_name='은행 순매수')),
                ('pension_fund', models.BigIntegerField(blank=True, help_text='연기금 등 순매수량 (API: penfnd_etc) - 국민연금 등', null=True, verbose_name='연기금 순매수')),
                ('private_fund', models.BigIntegerField(blank=True, help_text='사모펀드 순매수량 (API: samo_fund)', null=True, verbose_name='사모펀드 순매수')),
                ('other_corporation', models.BigIntegerField(blank=True, help_text='기타법인 순매수량 (API: etc_corp)', null=True, verbose_name='기타법인 순매수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('stock', models.ForeignKey(help_text='종목 정보 (Info 모델 참조)', on_delete=django.db.models.deletion.CASCADE, to='stocks.info', verbose_name='종목')),
            ],
            options={
                'verbose_name': '투자자별매매동향',
                'verbose_name_plural': '투자자별매매동향',
                'db_table': 'investor_trend',
                'ordering': ['-date', 'stock'],
                'indexes': [models.Index(fields=['stock', '-date'], name='investor_tr_stock_i_135bca_idx'), models.Index(fields=['-date'], name='investor_tr_date_28b2f9_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
