# Generated by Django 5.2.8 on 2025-11-29 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_dailychart'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='주봉 기준일자 (API: dt) - 해당 주의 마지막 거래일', verbose_name='일자')),
                ('opening_price', models.BigIntegerField(help_text='시가 (API: open_pric) - 해당 주 시작 가격', verbose_name='시가')),
                ('high_price', models.BigIntegerField(help_text='고가 (API: high_pric) - 해당 주 최고가', verbose_name='고가')),
                ('low_price', models.BigIntegerField(help_text='저가 (API: low_pric) - 해당 주 최저가', verbose_name='저가')),
                ('closing_price', models.BigIntegerField(help_text='종가/현재가 (API: cur_prc) - 해당 주 마감 가격', verbose_name='종가')),
                ('price_change', models.BigIntegerField(help_text='전주대비 (API: pred_pre) - 현재가 - 전주종가, 양수: 상승, 음수: 하락', verbose_name='전주대비')),
                ('trading_volume', models.BigIntegerField(help_text='거래량 (API: trde_qty) - 해당 주 총 거래량(주)', verbose_name='거래량')),
                ('trading_value', models.BigIntegerField(help_text='거래대금 (API: trde_prica) - 해당 주 총 거래금액(백만원)', verbose_name='거래대금')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('stock', models.ForeignKey(help_text='종목 정보 (Info 모델 참조)', on_delete=django.db.models.deletion.CASCADE, to='stocks.info', verbose_name='종목')),
            ],
            options={
                'verbose_name': '주봉차트',
                'verbose_name_plural': '주봉차트',
                'db_table': 'weekly_chart',
                'ordering': ['-date', 'stock'],
                'indexes': [models.Index(fields=['stock', '-date'], name='weekly_char_stock_i_a1fdd2_idx'), models.Index(fields=['-date'], name='weekly_char_date_7d77fe_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
