# Generated by Django 5.2.8 on 2025-11-29 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_monthlychart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortSelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='거래일자 (API: dt)', verbose_name='일자')),
                ('trading_volume', models.BigIntegerField(help_text='거래량 (API: trde_qty) - 당일 전체 거래량(주)', verbose_name='거래량')),
                ('short_volume', models.BigIntegerField(help_text='공매도량 (API: shrts_qty) - 당일 공매도 거래량(주)', verbose_name='공매도량')),
                ('cumulative_short_volume', models.BigIntegerField(help_text='누적공매도량 (API: ovr_shrts_qty) - 설정 기간의 공매도량 합산', verbose_name='누적공매도량')),
                ('trading_weight', models.DecimalField(decimal_places=2, help_text='매매비중 (API: trde_wght) - 전체 거래 대비 공매도 비중(%)', max_digits=5, verbose_name='매매비중')),
                ('short_trading_value', models.BigIntegerField(help_text='공매도거래대금 (API: shrts_trde_prica) - 당일 공매도 거래금액', verbose_name='공매도거래대금')),
                ('short_average_price', models.BigIntegerField(help_text='공매도평균가 (API: shrts_avg_pric) - 당일 공매도 평균 체결가', verbose_name='공매도평균가')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('stock', models.ForeignKey(help_text='종목 정보 (Info 모델 참조)', on_delete=django.db.models.deletion.CASCADE, to='stocks.info', verbose_name='종목')),
            ],
            options={
                'verbose_name': '공매도추이',
                'verbose_name_plural': '공매도추이',
                'db_table': 'short_selling',
                'ordering': ['-date', 'stock'],
                'indexes': [models.Index(fields=['stock', '-date'], name='short_selli_stock_i_71178b_idx'), models.Index(fields=['-date'], name='short_selli_date_e8e833_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
