# Generated by Django 5.2.8 on 2025-11-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_shortselling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='테마 고유 코드 (API: thema_grp_cd)', max_length=20, verbose_name='테마그룹코드')),
                ('name', models.CharField(help_text='테마 이름 (API: thema_nm) - 예: 2차전지, 반도체, AI 등', max_length=100, verbose_name='테마명')),
                ('date', models.DateField(db_index=True, help_text='거래일자 (DailyChart 기준)', verbose_name='일자')),
                ('stock_count', models.IntegerField(help_text='종목수 (API: stk_num) - 해당 테마에 속한 종목 개수', verbose_name='종목수')),
                ('rising_stock_count', models.IntegerField(help_text='상승종목수 (API: rising_stk_num) - 당일 상승한 종목 수', verbose_name='상승종목수')),
                ('falling_stock_count', models.IntegerField(help_text='하락종목수 (API: fall_stk_num) - 당일 하락한 종목 수', verbose_name='하락종목수')),
                ('fluctuation_rate', models.DecimalField(decimal_places=2, help_text='등락율 (API: flu_rt) - 당일 테마 평균 등락율(%)', max_digits=10, verbose_name='등락율')),
                ('period_profit_rate', models.DecimalField(decimal_places=2, help_text='기간수익률 (API: dt_prft_rt) - 특정 기간 동안의 수익률(%)', max_digits=10, verbose_name='기간수익률')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '테마통계',
                'verbose_name_plural': '테마통계',
                'db_table': 'theme',
                'ordering': ['-date', 'code'],
                'indexes': [models.Index(fields=['code', '-date'], name='theme_code_4b58f2_idx'), models.Index(fields=['-date'], name='theme_date_628848_idx'), models.Index(fields=['-period_profit_rate'], name='theme_period__fb99e3_idx')],
                'unique_together': {('code', 'date')},
            },
        ),
    ]
