# Generated by Django 5.2.8 on 2025-11-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='themes',
            field=models.ManyToManyField(blank=True, help_text='이 종목이 속한 테마들 (예: 반도체, AI, 2차전지 등)', related_name='stocks', to='stocks.theme', verbose_name='소속 테마'),
        ),
    ]
