# Generated by Django 5.2.8 on 2025-11-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_info_themes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='업종 고유 코드 (API: inds_cd)', max_length=20, verbose_name='업종코드')),
                ('name', models.CharField(help_text='업종 이름 (API: inds_nm) - 예: 은행, 반도체, 자동차 등', max_length=100, verbose_name='업종명')),
                ('date', models.DateField(db_index=True, help_text='거래일자 (DailyChart 기준)', verbose_name='일자')),
                ('market', models.CharField(choices=[('KOSPI', 'KOSPI'), ('KOSDAQ', 'KOSDAQ')], db_index=True, help_text='코스피(mrkt_tp=0) 또는 코스닥(mrkt_tp=1)', max_length=10, verbose_name='시장구분')),
                ('individual_net_buying', models.BigIntegerField(help_text='개인 순매수 (API: ind_netprps) - 양수: 순매수, 음수: 순매도', verbose_name='개인순매수')),
                ('foreign_net_buying', models.BigIntegerField(help_text='외국인 순매수 (API: frgnr_netprps)', verbose_name='외국인순매수')),
                ('institution_net_buying', models.BigIntegerField(help_text='기관계 전체 순매수 (API: orgn_netprps)', verbose_name='기관계순매수')),
                ('securities_net_buying', models.BigIntegerField(blank=True, help_text='증권사 순매수 (API: sc_netprps)', null=True, verbose_name='증권순매수')),
                ('insurance_net_buying', models.BigIntegerField(blank=True, help_text='보험 순매수 (API: insrnc_netprps)', null=True, verbose_name='보험순매수')),
                ('investment_trust_net_buying', models.BigIntegerField(blank=True, help_text='투신(투자신탁) 순매수 (API: invtrt_netprps)', null=True, verbose_name='투신순매수')),
                ('bank_net_buying', models.BigIntegerField(blank=True, help_text='은행 순매수 (API: bank_netprps)', null=True, verbose_name='은행순매수')),
                ('pension_fund_net_buying', models.BigIntegerField(blank=True, help_text='종신금 순매수 (API: jnsinkm_netprps)', null=True, verbose_name='종신금순매수')),
                ('endowment_net_buying', models.BigIntegerField(blank=True, help_text='기금 순매수 (API: endw_netprps)', null=True, verbose_name='기금순매수')),
                ('other_corporation_net_buying', models.BigIntegerField(blank=True, help_text='기타법인 순매수 (API: etc_corp_netprps)', null=True, verbose_name='기타법인순매수')),
                ('private_fund_net_buying', models.BigIntegerField(blank=True, help_text='사모펀드 순매수 (API: samo_fund_netprps)', null=True, verbose_name='사모펀드순매수')),
                ('domestic_foreign_net_buying', models.BigIntegerField(blank=True, help_text='내국인대우외국인 순매수 (API: native_trmt_frgnr_netprps)', null=True, verbose_name='내국인대우외국인순매수')),
                ('nation_net_buying', models.BigIntegerField(blank=True, help_text='국가 순매수 (API: natn_netprps)', null=True, verbose_name='국가순매수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '업종별순매수',
                'verbose_name_plural': '업종별순매수',
                'db_table': 'sector',
                'ordering': ['-date', 'market', 'code'],
                'indexes': [models.Index(fields=['code', 'market', '-date'], name='sector_code_ff600d_idx'), models.Index(fields=['-date', 'market'], name='sector_date_fe1a17_idx'), models.Index(fields=['market', '-date'], name='sector_market_f3e3aa_idx')],
                'unique_together': {('code', 'date', 'market')},
            },
        ),
    ]
