# Generated by Django 5.2.8 on 2025-11-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='sectors',
            field=models.ManyToManyField(blank=True, help_text='이 종목이 속한 업종들 (예: 종합, 대형주, 반도체업종 등)', related_name='stocks', to='stocks.sector', verbose_name='소속 업종'),
        ),
    ]
