# Generated by Django 5.2.8 on 2025-11-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_info_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='bps',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='BPS'),
        ),
        migrations.AddField(
            model_name='info',
            name='change_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='등락율'),
        ),
        migrations.AddField(
            model_name='info',
            name='credit_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='신용비율'),
        ),
        migrations.AddField(
            model_name='info',
            name='current_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='현재가'),
        ),
        migrations.AddField(
            model_name='info',
            name='eps',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='EPS'),
        ),
        migrations.AddField(
            model_name='info',
            name='ev',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='EV'),
        ),
        migrations.AddField(
            model_name='info',
            name='foreign_exhaustion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='외인소진률'),
        ),
        migrations.AddField(
            model_name='info',
            name='high_250',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='250최고'),
        ),
        migrations.AddField(
            model_name='info',
            name='high_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='고가'),
        ),
        migrations.AddField(
            model_name='info',
            name='listed_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='유통비율'),
        ),
        migrations.AddField(
            model_name='info',
            name='listed_shares',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='상장주식'),
        ),
        migrations.AddField(
            model_name='info',
            name='low_250',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='250최저'),
        ),
        migrations.AddField(
            model_name='info',
            name='low_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='저가'),
        ),
        migrations.AddField(
            model_name='info',
            name='net_income',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='당기순이익'),
        ),
        migrations.AddField(
            model_name='info',
            name='open_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='시가'),
        ),
        migrations.AddField(
            model_name='info',
            name='operating_profit',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='영업이익'),
        ),
        migrations.AddField(
            model_name='info',
            name='pbr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PBR'),
        ),
        migrations.AddField(
            model_name='info',
            name='per',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PER'),
        ),
        migrations.AddField(
            model_name='info',
            name='price_change',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='전일대비'),
        ),
        migrations.AddField(
            model_name='info',
            name='roe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='ROE'),
        ),
        migrations.AddField(
            model_name='info',
            name='sales',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='매출액'),
        ),
        migrations.AddField(
            model_name='info',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
        migrations.AddField(
            model_name='info',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='거래량'),
        ),
        migrations.AddField(
            model_name='info',
            name='volume_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='거래대비'),
        ),
        migrations.AddField(
            model_name='info',
            name='year_high',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='연중최고'),
        ),
        migrations.AddField(
            model_name='info',
            name='year_low',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='연중최저'),
        ),
    ]
