# Generated by Django 5.2.8 on 2025-12-01 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_info_bps_info_change_rate_info_credit_ratio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, help_text='회계연도 (예: 2024)', verbose_name='연도')),
                ('quarter', models.CharField(blank=True, db_index=True, help_text='분기 (1Q, 2Q, 3Q, 4Q) - null이면 연간 데이터', max_length=2, null=True, verbose_name='분기')),
                ('revenue', models.BigIntegerField(blank=True, help_text='매출액 (원 단위)', null=True, verbose_name='매출액')),
                ('operating_profit', models.BigIntegerField(blank=True, help_text='영업이익 (원 단위)', null=True, verbose_name='영업이익')),
                ('net_income', models.BigIntegerField(blank=True, help_text='당기순이익 (원 단위)', null=True, verbose_name='순이익')),
                ('revenue_growth', models.DecimalField(blank=True, decimal_places=2, help_text='전분기/전년 대비 매출액 증가율 (%)', max_digits=10, null=True, verbose_name='매출액증가율')),
                ('operating_profit_growth', models.DecimalField(blank=True, decimal_places=2, help_text='전분기/전년 대비 영업이익 증가율 (%)', max_digits=10, null=True, verbose_name='영업이익증가율')),
                ('net_income_growth', models.DecimalField(blank=True, decimal_places=2, help_text='전분기/전년 대비 순이익 증가율 (%)', max_digits=10, null=True, verbose_name='순이익증가율')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('stock', models.ForeignKey(help_text='종목 정보 (Info 모델 참조)', on_delete=django.db.models.deletion.CASCADE, to='stocks.info', verbose_name='종목')),
            ],
            options={
                'verbose_name': '재무제표',
                'verbose_name_plural': '재무제표',
                'db_table': 'financial',
                'ordering': ['-year', '-quarter'],
                'indexes': [models.Index(fields=['stock', '-year', '-quarter'], name='financial_stock_i_ac6b09_idx'), models.Index(fields=['-year', '-quarter'], name='financial_year_0ccfc5_idx')],
                'unique_together': {('stock', 'year', 'quarter')},
            },
        ),
    ]
