# Generated by Django 5.2.8 on 2025-12-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_financial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial',
            name='is_estimated',
            field=models.BooleanField(default=False, help_text='네이버 금융 (E) 표시 - True면 추정치', verbose_name='추정치여부'),
        ),
        migrations.AddField(
            model_name='financial',
            name='net_margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='당기순이익 / 매출액 * 100 (%)', max_digits=10, null=True, verbose_name='순이익률'),
        ),
        migrations.AddField(
            model_name='financial',
            name='operating_margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='영업이익 / 매출액 * 100 (%)', max_digits=10, null=True, verbose_name='영업이익률'),
        ),
        migrations.AddField(
            model_name='financial',
            name='roe',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='자기자본이익률 (지배주주 기준, %)', max_digits=10, null=True, verbose_name='ROE'),
        ),
    ]
