# Generated by Django 5.2.8 on 2025-12-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_financial_is_estimated_financial_net_margin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='roe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ROE'),
        ),
    ]
