# Generated by Django 5.2.8 on 2025-12-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_alter_info_roe'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='interest_level',
            field=models.CharField(blank=True, choices=[('super', '초관심'), ('normal', '관심'), ('incubator', '인큐베이터')], help_text='투자 관심 단계 (초관심 > 관심 > 인큐베이터)', max_length=10, null=True, verbose_name='관심단계'),
        ),
    ]
