# Generated by Django 5.2.8 on 2025-12-04 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_info_interest_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField(help_text='FnGuide 리포트 고유 ID (API: RPT_ID)', unique=True, verbose_name='리포트ID')),
                ('date', models.DateField(db_index=True, help_text='리포트 발행일 (API: ANL_DT)', verbose_name='발행일')),
                ('title', models.CharField(help_text='리포트 제목 (API: RPT_TITLE)', max_length=500, verbose_name='제목')),
                ('author', models.CharField(help_text='애널리스트명 (API: ANL_NM_KOR) - 복수인 경우 콤마로 구분', max_length=100, verbose_name='작성자')),
                ('provider', models.CharField(help_text='증권사명 (API: BRK_NM_KOR)', max_length=100, verbose_name='제공처')),
                ('target_price', models.BigIntegerField(blank=True, help_text='목표주가 (API: TARGET_PRC) - 없는 경우 null', null=True, verbose_name='목표가')),
                ('recommendation', models.CharField(blank=True, help_text='투자의견 (API: RECOMM) - BUY, HOLD, SELL 등', max_length=20, null=True, verbose_name='투자의견')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('stock', models.ForeignKey(help_text='종목 정보 (Info 모델 참조)', on_delete=django.db.models.deletion.CASCADE, to='stocks.info', verbose_name='종목')),
            ],
            options={
                'verbose_name': '애널리스트리포트',
                'verbose_name_plural': '애널리스트리포트',
                'db_table': 'report',
                'ordering': ['-date', 'stock'],
                'indexes': [models.Index(fields=['stock', '-date'], name='report_stock_i_e3efe5_idx'), models.Index(fields=['-date'], name='report_date_c9a4ab_idx')],
            },
        ),
    ]
