# Generated by Django 5.2.8 on 2025-12-05 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_add_report_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_index=True, help_text='기사 발행일', null=True, verbose_name='발행일')),
                ('title', models.CharField(help_text='기사 제목', max_length=500, verbose_name='제목')),
                ('link', models.URLField(help_text='기사 URL', max_length=500, verbose_name='링크')),
                ('summary', models.TextField(blank=True, help_text='기사 요약 내용', verbose_name='요약')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('stock', models.ForeignKey(help_text='종목 정보 (Info 모델 참조)', on_delete=django.db.models.deletion.CASCADE, to='stocks.info', verbose_name='종목')),
            ],
            options={
                'verbose_name': '노다지기사',
                'verbose_name_plural': '노다지기사',
                'db_table': 'nodaji',
                'ordering': ['-date', 'stock'],
                'indexes': [models.Index(fields=['stock', '-date'], name='nodaji_stock_i_16e3cc_idx'), models.Index(fields=['-date'], name='nodaji_date_965a49_idx')],
            },
        ),
    ]
