# Generated by Django 5.2.8 on 2025-12-05 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0017_nodaji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gongsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_index=True, help_text='공시 접수일', null=True, verbose_name='접수일')),
                ('title', models.CharField(help_text='공시 보고서명', max_length=500, verbose_name='보고서명')),
                ('link', models.URLField(help_text='DART 공시 URL', max_length=500, verbose_name='링크')),
                ('submitter', models.CharField(blank=True, help_text='공시 제출인', max_length=100, verbose_name='제출인')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('stock', models.ForeignKey(help_text='종목 정보 (Info 모델 참조)', on_delete=django.db.models.deletion.CASCADE, to='stocks.info', verbose_name='종목')),
            ],
            options={
                'verbose_name': '공시',
                'verbose_name_plural': '공시',
                'db_table': 'gongsi',
                'ordering': ['-date', 'stock'],
                'indexes': [models.Index(fields=['stock', '-date'], name='gongsi_stock_i_ae9cb3_idx'), models.Index(fields=['-date'], name='gongsi_date_b0bdc4_idx')],
            },
        ),
    ]
