# Generated by Django 5.2.8 on 2025-12-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_gongsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='investment_point',
            field=models.TextField(blank=True, default='', help_text='투자포인트 (HTML 형식)', verbose_name='투자포인트'),
        ),
        migrations.AddField(
            model_name='info',
            name='risk',
            field=models.TextField(blank=True, default='', help_text='리스크 (HTML 형식)', verbose_name='리스크'),
        ),
    ]
