# Generated by Django 5.2.8 on 2025-12-05 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0019_info_investment_point_info_risk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_text', models.CharField(help_text='표시용 날짜 텍스트 (예: "내년 상반기", "2025-03-15")', max_length=50, verbose_name='날짜(표시)')),
                ('date_sort', models.DateField(blank=True, db_index=True, help_text='정렬/알림용 날짜 (대략적인 날짜, 선택사항)', null=True, verbose_name='알림일자')),
                ('content', models.CharField(help_text='일정 내용', max_length=200, verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='stocks.info', verbose_name='종목')),
            ],
            options={
                'verbose_name': '일정',
                'verbose_name_plural': '일정',
                'db_table': 'schedule',
                'ordering': ['date_sort', 'stock'],
                'indexes': [models.Index(fields=['stock', 'date_sort'], name='schedule_stock_i_f90695_idx'), models.Index(fields=['date_sort'], name='schedule_date_so_1fec78_idx')],
            },
        ),
    ]
