# Generated by Django 5.2.8 on 2025-12-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0020_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='지수 코드 (KOSPI, KOSDAQ)', max_length=10, verbose_name='지수코드')),
                ('date', models.DateField(db_index=True, verbose_name='일자')),
                ('opening_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='시가')),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='고가')),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='저가')),
                ('closing_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='종가')),
                ('trading_volume', models.BigIntegerField(verbose_name='거래량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '지수차트',
                'verbose_name_plural': '지수차트',
                'db_table': 'index_chart',
                'ordering': ['-date', 'code'],
                'indexes': [models.Index(fields=['code', '-date'], name='index_chart_code_685bab_idx'), models.Index(fields=['-date'], name='index_chart_date_c06489_idx')],
                'unique_together': {('code', 'date')},
            },
        ),
    ]
