# Generated by Django 5.2.8 on 2025-12-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0021_indexchart'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(db_index=True, help_text='KOSPI, KOSDAQ, FUTURES', max_length=10, verbose_name='시장')),
                ('date', models.DateField(db_index=True, verbose_name='일자')),
                ('individual', models.BigIntegerField(help_text='개인 순매수 (백만원)', verbose_name='개인')),
                ('foreign', models.BigIntegerField(help_text='외국인 순매수 (백만원)', verbose_name='외국인')),
                ('institution', models.BigIntegerField(help_text='기관 전체 순매수 (백만원)', verbose_name='기관계')),
                ('financial_investment', models.BigIntegerField(blank=True, help_text='금융투자 순매수 (백만원)', null=True, verbose_name='금융투자')),
                ('insurance', models.BigIntegerField(blank=True, help_text='보험 순매수 (백만원)', null=True, verbose_name='보험')),
                ('trust', models.BigIntegerField(blank=True, help_text='투신/사모 순매수 (백만원)', null=True, verbose_name='투신(사모)')),
                ('bank', models.BigIntegerField(blank=True, help_text='은행 순매수 (백만원)', null=True, verbose_name='은행')),
                ('other_financial', models.BigIntegerField(blank=True, help_text='기타금융기관 순매수 (백만원)', null=True, verbose_name='기타금융기관')),
                ('pension_fund', models.BigIntegerField(blank=True, help_text='연기금 등 순매수 (백만원)', null=True, verbose_name='연기금등')),
                ('other_corporation', models.BigIntegerField(blank=True, help_text='기타법인 순매수 (백만원)', null=True, verbose_name='기타법인')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '시장별매매동향',
                'verbose_name_plural': '시장별매매동향',
                'db_table': 'market_trend',
                'ordering': ['-date', 'market'],
                'indexes': [models.Index(fields=['market', '-date'], name='market_tren_market_4fc1f1_idx'), models.Index(fields=['-date'], name='market_tren_date_d4b13d_idx')],
                'unique_together': {('market', 'date')},
            },
        ),
    ]
