# Generated by Django 5.2.8 on 2025-12-05 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0022_markettrend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='themes',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
