# Generated by Django 5.2.8 on 2025-12-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0023_remove_info_themes_delete_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='is_holding',
            field=models.BooleanField(default=False, help_text='현재 보유 중인 종목 여부', verbose_name='보유중'),
        ),
    ]
