# Generated by Django 5.2.8 on 2025-12-05 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0024_add_is_holding_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='업종 소분류 이름 (최대 20자)', max_length=20, verbose_name='소분류명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '업종 소분류',
                'verbose_name_plural': '업종 소분류',
                'db_table': 'theme',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ThemeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='업종 대분류 이름 (최대 20자)', max_length=20, unique=True, verbose_name='대분류명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '업종 대분류',
                'verbose_name_plural': '업종 대분류',
                'db_table': 'theme_category',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='info',
            name='themes',
            field=models.ManyToManyField(blank=True, help_text='사용자 정의 업종 (반도체, 전기전력 등)', related_name='stocks', to='stocks.theme', verbose_name='업종'),
        ),
        migrations.AddField(
            model_name='theme',
            name='category',
            field=models.ForeignKey(help_text='소속 대분류', on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='stocks.themecategory', verbose_name='대분류'),
        ),
        migrations.AlterUniqueTogether(
            name='theme',
            unique_together={('category', 'name')},
        ),
    ]
