# Generated by Django 5.2.8 on 2025-12-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0025_add_theme_two_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='analysis',
            field=models.TextField(blank=True, default='', help_text='기업분석 (HTML 형식)', verbose_name='기업분석'),
        ),
    ]
