# Generated by Django 5.2.8 on 2025-12-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0026_add_analysis_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoETF',
            fields=[
                ('code', models.CharField(help_text='ETF 종목코드 (6자리)', max_length=10, primary_key=True, serialize=False, verbose_name='종목코드')),
                ('name', models.CharField(help_text='ETF 종목명', max_length=100, verbose_name='종목명')),
                ('is_active', models.BooleanField(default=True, help_text='활성 상태 여부', verbose_name='활성화')),
                ('current_price', models.BigIntegerField(blank=True, help_text='현재가 (원)', null=True, verbose_name='현재가')),
                ('change_rate', models.DecimalField(blank=True, decimal_places=2, help_text='전일대비 등락률 (%)', max_digits=6, null=True, verbose_name='등락률')),
                ('nav', models.BigIntegerField(blank=True, help_text='순자산가치 (원)', null=True, verbose_name='NAV')),
                ('market_cap', models.BigIntegerField(blank=True, help_text='시가총액 (억원 단위)', null=True, verbose_name='시가총액')),
                ('management_fee', models.DecimalField(blank=True, decimal_places=3, help_text='총보수 (%, 예: 0.150)', max_digits=5, null=True, verbose_name='총보수')),
                ('holdings', models.JSONField(blank=True, default=list, help_text='구성종목 리스트 [{name, ratio}, ...]', verbose_name='구성종목')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': 'ETF 종목정보',
                'verbose_name_plural': 'ETF 종목정보',
                'db_table': 'info_etf',
                'ordering': ['-market_cap', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='info',
            name='market',
            field=models.CharField(choices=[('KOSPI', 'KOSPI'), ('KOSDAQ', 'KOSDAQ'), ('KONEX', 'KONEX'), ('ETF', 'ETF')], max_length=10, verbose_name='시장구분'),
        ),
    ]
