# Generated by Django 5.2.8 on 2025-12-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0027_create_info_etf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='market',
            field=models.CharField(choices=[('KOSPI', 'KOSPI'), ('KOSDAQ', 'KOSDAQ'), ('KONEX', 'KONEX')], max_length=10, verbose_name='시장구분'),
        ),
    ]
