# Generated by Django 5.2.8 on 2025-12-06 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0028_remove_etf_from_info_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChartETF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='일자')),
                ('opening_price', models.BigIntegerField(verbose_name='시가')),
                ('high_price', models.BigIntegerField(verbose_name='고가')),
                ('low_price', models.BigIntegerField(verbose_name='저가')),
                ('closing_price', models.BigIntegerField(verbose_name='종가')),
                ('trading_volume', models.BigIntegerField(verbose_name='거래량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.infoetf', verbose_name='ETF')),
            ],
            options={
                'verbose_name': 'ETF 일봉차트',
                'verbose_name_plural': 'ETF 일봉차트',
                'db_table': 'daily_chart_etf',
                'ordering': ['-date', 'etf'],
                'indexes': [models.Index(fields=['etf', '-date'], name='daily_chart_etf_id_ece2f2_idx'), models.Index(fields=['-date'], name='daily_chart_date_d9b6c4_idx')],
                'unique_together': {('etf', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyChartETF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='일자')),
                ('opening_price', models.BigIntegerField(verbose_name='시가')),
                ('high_price', models.BigIntegerField(verbose_name='고가')),
                ('low_price', models.BigIntegerField(verbose_name='저가')),
                ('closing_price', models.BigIntegerField(verbose_name='종가')),
                ('trading_volume', models.BigIntegerField(verbose_name='거래량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.infoetf', verbose_name='ETF')),
            ],
            options={
                'verbose_name': 'ETF 월봉차트',
                'verbose_name_plural': 'ETF 월봉차트',
                'db_table': 'monthly_chart_etf',
                'ordering': ['-date', 'etf'],
                'indexes': [models.Index(fields=['etf', '-date'], name='monthly_cha_etf_id_a20c76_idx'), models.Index(fields=['-date'], name='monthly_cha_date_e43170_idx')],
                'unique_together': {('etf', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyChartETF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='일자')),
                ('opening_price', models.BigIntegerField(verbose_name='시가')),
                ('high_price', models.BigIntegerField(verbose_name='고가')),
                ('low_price', models.BigIntegerField(verbose_name='저가')),
                ('closing_price', models.BigIntegerField(verbose_name='종가')),
                ('trading_volume', models.BigIntegerField(verbose_name='거래량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.infoetf', verbose_name='ETF')),
            ],
            options={
                'verbose_name': 'ETF 주봉차트',
                'verbose_name_plural': 'ETF 주봉차트',
                'db_table': 'weekly_chart_etf',
                'ordering': ['-date', 'etf'],
                'indexes': [models.Index(fields=['etf', '-date'], name='weekly_char_etf_id_c3da18_idx'), models.Index(fields=['-date'], name='weekly_char_date_703690_idx')],
                'unique_together': {('etf', 'date')},
            },
        ),
    ]
