# Generated by Django 5.2.8 on 2025-12-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0029_create_etf_chart_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='표시용 작업 이름 (예: 일봉 데이터 수집)', max_length=100, verbose_name='작업명')),
                ('command', models.CharField(help_text='실행할 management command (예: save_daily_chart --code all --mode today)', max_length=200, verbose_name='명령어')),
                ('run_time', models.TimeField(help_text='실행 시간 (HH:MM)', verbose_name='실행시간')),
                ('weekdays', models.CharField(default='1,2,3,4,5', help_text='실행할 요일 (1=월, 2=화, ..., 7=일) 콤마로 구분', max_length=20, verbose_name='실행요일')),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부', verbose_name='활성화')),
                ('last_run', models.DateTimeField(blank=True, help_text='마지막 실행 일시', null=True, verbose_name='마지막실행')),
                ('last_result', models.CharField(blank=True, choices=[('success', '성공'), ('failure', '실패'), ('running', '실행중')], help_text='마지막 실행 결과', max_length=20, null=True, verbose_name='실행결과')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '크론잡',
                'verbose_name_plural': '크론잡',
                'db_table': 'cron_job',
                'ordering': ['run_time', 'name'],
            },
        ),
    ]
