# Generated by Django 5.2.8 on 2025-12-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0030_create_cronjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='fav_sync_status',
            field=models.CharField(blank=True, choices=[('syncing', '동기화 중'), ('completed', '완료'), ('deleting', '삭제 중')], max_length=20, null=True, verbose_name='관심종목 동기화 상태'),
        ),
    ]
