# Generated by Django 5.2.8 on 2025-12-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0032_add_excluded_youtube_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredYoutubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='선호 유튜브 채널명', max_length=100, unique=True, verbose_name='채널명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
            ],
            options={
                'verbose_name': '유튜브 선호 채널',
                'verbose_name_plural': '유튜브 선호 채널',
                'db_table': 'preferred_youtube_channel',
                'ordering': ['name'],
            },
        ),
    ]
