# Generated by Django 5.2.8 on 2025-12-09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0033_add_preferred_youtube_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(help_text='유튜브 영상 고유 ID', max_length=20, verbose_name='영상ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('channel', models.CharField(max_length=100, verbose_name='채널명')),
                ('thumbnail', models.URLField(blank=True, max_length=500, verbose_name='썸네일')),
                ('duration', models.CharField(blank=True, max_length=20, verbose_name='재생시간')),
                ('views', models.CharField(blank=True, max_length=50, verbose_name='조회수')),
                ('published', models.CharField(blank=True, max_length=50, verbose_name='업로드일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='저장일시')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_videos', to='stocks.info', verbose_name='종목')),
            ],
            options={
                'verbose_name': '유튜브 영상',
                'verbose_name_plural': '유튜브 영상',
                'db_table': 'youtube_video',
                'ordering': ['-created_at'],
                'unique_together': {('stock', 'video_id')},
            },
        ),
    ]
