# Generated by Django 5.2.8 on 2025-12-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0034_add_youtube_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='summary',
            field=models.TextField(blank=True, help_text='영상 요약 내용', verbose_name='요약'),
        ),
    ]
