# Generated by Django 5.2.8 on 2025-12-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0038_info_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='설정키')),
                ('value', models.TextField(blank=True, verbose_name='설정값')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '시스템 설정',
                'verbose_name_plural': '시스템 설정',
                'db_table': 'system_setting',
            },
        ),
    ]
