# Generated by Django 5.2.8 on 2025-12-13 10:56

import re
from django.db import migrations


def clean_html_fields(apps, schema_editor):
    """빈 HTML 콘텐츠를 정리하고, HTML을 텍스트로 변환"""
    Info = apps.get_model('stocks', 'Info')

    # 빈 HTML 패턴 (Quill 에디터가 생성하는 빈 콘텐츠)
    empty_html_patterns = [
        r'^<p><br></p>$',
        r'^<p></p>$',
        r'^<p>\s*</p>$',
        r'^\s*$',
    ]

    def is_empty_html(content):
        if not content:
            return True
        content = content.strip()
        for pattern in empty_html_patterns:
            if re.match(pattern, content, re.IGNORECASE):
                return True
        return False

    def html_to_text(content):
        """HTML을 텍스트로 변환 (간단한 변환)"""
        if not content:
            return ''
        # 빈 HTML이면 빈 문자열 반환
        if is_empty_html(content):
            return ''
        # HTML 태그가 있는지 확인
        if not re.search(r'<[a-z][\s\S]*>', content, re.IGNORECASE):
            return content  # HTML이 아니면 그대로 반환

        # 줄바꿈 변환
        text = re.sub(r'<br\s*/?>', '\n', content, flags=re.IGNORECASE)
        text = re.sub(r'</p>\s*<p>', '\n\n', text, flags=re.IGNORECASE)
        text = re.sub(r'</(div|p|h[1-6]|li)>', '\n', text, flags=re.IGNORECASE)
        # 리스트 항목
        text = re.sub(r'<li[^>]*>', '- ', text, flags=re.IGNORECASE)
        # 모든 태그 제거
        text = re.sub(r'<[^>]+>', '', text)
        # HTML 엔티티 변환
        text = text.replace('&nbsp;', ' ')
        text = text.replace('&amp;', '&')
        text = text.replace('&lt;', '<')
        text = text.replace('&gt;', '>')
        text = text.replace('&quot;', '"')
        # 여러 줄바꿈 정리
        text = re.sub(r'\n{3,}', '\n\n', text)
        return text.strip()

    fields = ['investment_point', 'risk', 'memo', 'analysis']
    updated_count = 0

    for info in Info.objects.all():
        changed = False
        for field in fields:
            old_value = getattr(info, field)
            new_value = html_to_text(old_value)
            if old_value != new_value:
                setattr(info, field, new_value)
                changed = True
        if changed:
            info.save()
            updated_count += 1

    print(f'Cleaned HTML data for {updated_count} stocks')


def reverse_clean(apps, schema_editor):
    # 되돌리기 불가 (데이터 변환은 일방향)
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0039_systemsetting'),
    ]

    operations = [
        migrations.RunPython(clean_html_fields, reverse_clean),
    ]
