# Generated by Django 5.2.8 on 2025-12-13 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0040_clean_html_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='analysis',
        ),
    ]
