# Generated by Django 5.2.8 on 2025-12-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0041_remove_analysis_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='summary',
            field=models.TextField(blank=True, help_text='리포트 요약 내용', verbose_name='요약'),
        ),
    ]
