# Generated by Django 5.2.8 on 2025-12-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0042_add_report_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='analysis_text',
            field=models.TextField(blank=True, default='', help_text='기업분석 내용 (마크다운 형식)', verbose_name='기업분석(텍스트)'),
        ),
    ]
