# Generated by Django 5.2.8 on 2025-12-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0045_add_updated_at_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='섹터 이름 (예: 화장품, 2차전지)', max_length=50, unique=True, verbose_name='섹터명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '사용자정의섹터',
                'verbose_name_plural': '사용자정의섹터',
                'db_table': 'custom_sector',
                'ordering': ['name'],
            },
        ),
    ]
