# Generated by Django 5.2.8 on 2025-12-25 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0046_add_custom_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='제목')),
                ('link', models.URLField(max_length=1000, verbose_name='링크')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='출처')),
                ('published', models.CharField(blank=True, max_length=50, verbose_name='게시일')),
                ('summary', models.TextField(blank=True, help_text='뉴스 요약 내용', verbose_name='요약')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='저장일시')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to='stocks.info', verbose_name='종목')),
            ],
            options={
                'verbose_name': '뉴스',
                'verbose_name_plural': '뉴스',
                'db_table': 'news',
                'ordering': ['-created_at'],
                'unique_together': {('stock', 'link')},
            },
        ),
    ]
