# Generated by Django 5.2.8 on 2025-12-25 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0048_telegrammessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorTelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=100, verbose_name='채널')),
                ('channel_name', models.CharField(blank=True, max_length=100, verbose_name='채널명')),
                ('date', models.CharField(max_length=20, verbose_name='날짜')),
                ('time', models.CharField(max_length=20, verbose_name='시간')),
                ('text', models.TextField(verbose_name='내용')),
                ('summary', models.TextField(blank=True, help_text='메시지 요약 내용', verbose_name='요약')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='저장일시')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_messages', to='stocks.customsector', verbose_name='섹터')),
            ],
            options={
                'verbose_name': '섹터 텔레그램 메시지',
                'verbose_name_plural': '섹터 텔레그램 메시지',
                'db_table': 'sector_telegram_message',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
