# Generated by Django 5.2.8 on 2025-12-25 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0049_sectortelegrammessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='제목')),
                ('link', models.URLField(max_length=1000, verbose_name='링크')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='출처')),
                ('published', models.CharField(blank=True, max_length=50, verbose_name='게시일')),
                ('summary', models.TextField(blank=True, help_text='뉴스 요약 내용', verbose_name='요약')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='저장일시')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to='stocks.customsector', verbose_name='섹터')),
            ],
            options={
                'verbose_name': '섹터 뉴스',
                'verbose_name_plural': '섹터 뉴스',
                'db_table': 'sector_news',
                'ordering': ['-created_at'],
                'unique_together': {('sector', 'link')},
            },
        ),
    ]
