# Generated by Django 5.2.8 on 2025-12-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0052_add_custom_sectors_to_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsector',
            name='memo',
            field=models.TextField(blank=True, default='', help_text='사용자 메모', verbose_name='메모'),
        ),
        migrations.AddField(
            model_name='customsector',
            name='negative',
            field=models.TextField(blank=True, default='', help_text='악재 (줄바꿈으로 구분)', verbose_name='악재'),
        ),
        migrations.AddField(
            model_name='customsector',
            name='positive',
            field=models.TextField(blank=True, default='', help_text='호재 (줄바꿈으로 구분)', verbose_name='호재'),
        ),
        migrations.AddField(
            model_name='customsector',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='섹터 요약', verbose_name='요약'),
        ),
        migrations.AddField(
            model_name='customsector',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
    ]
