# Generated by Django 5.2.8 on 2025-12-26 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0053_add_sector_dashboard_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsector',
            name='negative',
        ),
        migrations.RemoveField(
            model_name='customsector',
            name='positive',
        ),
    ]
