# Generated by Django 5.2.8 on 2025-12-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0054_remove_positive_negative_from_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoetf',
            name='custom_sectors',
            field=models.ManyToManyField(blank=True, help_text='사용자 정의 섹터 (화장품, 2차전지 등)', related_name='etfs', to='stocks.customsector', verbose_name='관심섹터'),
        ),
    ]
