# Generated by Django 5.2.8 on 2025-12-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0055_add_etf_custom_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsector',
            name='base_prompt',
            field=models.TextField(blank=True, default='', help_text='AI 분석용 베이스 프롬프트', verbose_name='베이스 프롬프트'),
        ),
        migrations.AddField(
            model_name='customsector',
            name='basic_report',
            field=models.TextField(blank=True, default='', help_text='기초리포트 (HTML 형식)', verbose_name='기초리포트'),
        ),
        migrations.AddField(
            model_name='customsector',
            name='integrated_report',
            field=models.TextField(blank=True, default='', help_text='통합리포트 (HTML 형식)', verbose_name='통합리포트'),
        ),
        migrations.AddField(
            model_name='customsector',
            name='question_prompt',
            field=models.TextField(blank=True, default='', help_text='AI 질문용 프롬프트', verbose_name='질문 프롬프트'),
        ),
    ]
