# Generated by Django 5.2.8 on 2025-12-27 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0056_add_sector_report_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsector',
            name='summary',
        ),
    ]
