# Generated by Django 5.2.8 on 2025-12-27 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0057_remove_sector_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsector',
            name='base_prompt',
        ),
        migrations.RemoveField(
            model_name='customsector',
            name='question_prompt',
        ),
    ]
