# Generated by Django 5.2.8 on 2025-12-27 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0058_remove_sector_prompts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsector',
            name='integrated_report',
        ),
        migrations.CreateModel(
            name='SectorQuestionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='질문 내용', verbose_name='질문')),
                ('report', models.TextField(blank=True, default='', help_text='리포트 (HTML 형식)', verbose_name='리포트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('sector', models.ForeignKey(help_text='관련 섹터', on_delete=django.db.models.deletion.CASCADE, related_name='question_reports', to='stocks.customsector', verbose_name='섹터')),
            ],
            options={
                'verbose_name': '섹터질문리포트',
                'verbose_name_plural': '섹터질문리포트',
                'db_table': 'sector_question_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
