# Generated by Django 5.2.8 on 2026-01-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0060_add_stock_question_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='investortrend',
            name='daum_foreign',
            field=models.BigIntegerField(blank=True, help_text='다음 금융 외국인 순매수량 (API: foreignStraightPurchaseVolume)', null=True, verbose_name='외국인 순매수(다음)'),
        ),
        migrations.AddField(
            model_name='investortrend',
            name='daum_institution',
            field=models.BigIntegerField(blank=True, help_text='다음 금융 기관 순매수량 (API: institutionStraightPurchaseVolume)', null=True, verbose_name='기관 순매수(다음)'),
        ),
    ]
