# Generated by Django 5.2.8 on 2026-01-10 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0061_add_daum_investor_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorUploadedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='업로드된 리포트 파일 (PDF 등)', upload_to='uploaded_reports/sector/%Y/%m/', verbose_name='파일')),
                ('original_filename', models.CharField(help_text='업로드 시 원본 파일명', max_length=255, verbose_name='원본파일명')),
                ('summary', models.TextField(blank=True, default='', help_text='리포트 요약 내용 (HTML 형식)', verbose_name='요약')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('sector', models.ForeignKey(help_text='관련 섹터', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_reports', to='stocks.customsector', verbose_name='섹터')),
            ],
            options={
                'verbose_name': '섹터업로드리포트',
                'verbose_name_plural': '섹터업로드리포트',
                'db_table': 'sector_uploaded_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockUploadedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='업로드된 리포트 파일 (PDF 등)', upload_to='uploaded_reports/stock/%Y/%m/', verbose_name='파일')),
                ('original_filename', models.CharField(help_text='업로드 시 원본 파일명', max_length=255, verbose_name='원본파일명')),
                ('summary', models.TextField(blank=True, default='', help_text='리포트 요약 내용 (HTML 형식)', verbose_name='요약')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('stock', models.ForeignKey(help_text='관련 종목', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_reports', to='stocks.info', verbose_name='종목')),
            ],
            options={
                'verbose_name': '종목업로드리포트',
                'verbose_name_plural': '종목업로드리포트',
                'db_table': 'stock_uploaded_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
