# Generated by Django 5.2.8 on 2026-01-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0062_sectoruploadedreport_stockuploadedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectoruploadedreport',
            name='title',
            field=models.CharField(blank=True, default='', help_text='사용자 지정 제목 (비어있으면 원본파일명 사용)', max_length=255, verbose_name='제목'),
        ),
        migrations.AddField(
            model_name='stockuploadedreport',
            name='title',
            field=models.CharField(blank=True, default='', help_text='사용자 지정 제목 (비어있으면 원본파일명 사용)', max_length=255, verbose_name='제목'),
        ),
    ]
