# Generated by Django 5.2.8 on 2026-01-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0063_sectoruploadedreport_title_stockuploadedreport_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='key_briefing',
            field=models.TextField(blank=True, default='', help_text='투자포인트/리스크/일정 핵심 요약 (마크다운 형식)', verbose_name='핵심 브리핑'),
        ),
        migrations.AddField(
            model_name='info',
            name='key_briefing_updated_at',
            field=models.DateField(blank=True, help_text='핵심 브리핑 마지막 수정일', null=True, verbose_name='핵심 브리핑 업데이트일'),
        ),
    ]
