# Generated by Django 5.2.8 on 2026-01-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0064_add_key_briefing_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorquestionreport',
            name='report_type',
            field=models.CharField(choices=[('html', 'HTML'), ('markdown', '마크다운')], default='html', help_text='리포트의 형식 (HTML 또는 마크다운)', max_length=10, verbose_name='리포트 형식'),
        ),
        migrations.AddField(
            model_name='stockquestionreport',
            name='report_type',
            field=models.CharField(choices=[('html', 'HTML'), ('markdown', '마크다운')], default='html', help_text='리포트의 형식 (HTML 또는 마크다운)', max_length=10, verbose_name='리포트 형식'),
        ),
        migrations.AlterField(
            model_name='sectorquestionreport',
            name='report',
            field=models.TextField(blank=True, default='', help_text='리포트 내용 (HTML 또는 마크다운)', verbose_name='리포트'),
        ),
        migrations.AlterField(
            model_name='stockquestionreport',
            name='report',
            field=models.TextField(blank=True, default='', help_text='리포트 내용 (HTML 또는 마크다운)', verbose_name='리포트'),
        ),
    ]
