# Generated by Django 5.2.8 on 2026-01-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0065_add_report_type_to_question_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, help_text='리포트 PDF 파일', null=True, upload_to='reports/%Y/%m/', verbose_name='첨부파일'),
        ),
    ]
