# Generated by Django 5.2.8 on 2026-01-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0066_add_file_to_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='analysis_type',
            field=models.CharField(choices=[('html', 'HTML'), ('markdown', '마크다운')], default='html', help_text='HTML 또는 마크다운', max_length=10, verbose_name='기업분석 타입'),
        ),
        migrations.AlterField(
            model_name='info',
            name='analysis_text',
            field=models.TextField(blank=True, default='', help_text='기업분석 내용', verbose_name='기업분석(텍스트)'),
        ),
    ]
