# Generated by Django 5.2.8 on 2026-01-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0067_add_analysis_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='질문')),
                ('prompt', models.TextField(blank=True, verbose_name='프롬프트')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '리서치 프롬프트',
                'verbose_name_plural': '리서치 프롬프트',
                'db_table': 'research_prompt',
                'ordering': ['order', 'id'],
            },
        ),
    ]
