# Generated by Django 5.2.8 on 2026-01-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0068_add_research_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchprompt',
            name='needs_attachment',
            field=models.BooleanField(default=False, verbose_name='첨부파일 필요'),
        ),
    ]
