# Generated by Django 5.2.8 on 2026-04-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0074_add_valuation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketYoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(help_text='유튜브 영상 고유 ID', max_length=20, unique=True, verbose_name='영상ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('channel', models.CharField(blank=True, max_length=100, verbose_name='채널명')),
                ('summary', models.TextField(blank=True, help_text='영상 요약 내용', verbose_name='요약')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='저장일시')),
            ],
            options={
                'verbose_name': '시황 유튜브 영상',
                'verbose_name_plural': '시황 유튜브 영상',
                'db_table': 'market_youtube_video',
                'ordering': ['-created_at'],
            },
        ),
    ]
