# Generated by Django 5.2.8 on 2026-04-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0075_marketyoutubevideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketyoutubevideo',
            options={'ordering': ['-published_date', '-created_at'], 'verbose_name': '시황 유튜브 영상', 'verbose_name_plural': '시황 유튜브 영상'},
        ),
        migrations.AddField(
            model_name='marketyoutubevideo',
            name='published_date',
            field=models.DateField(blank=True, null=True, verbose_name='영상 게시일'),
        ),
    ]
