# Generated by Django 5.2.8 on 2026-04-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0076_alter_marketyoutubevideo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketyoutubevideo',
            name='note',
            field=models.CharField(blank=True, help_text='간단한 요약 메모', max_length=300, verbose_name='메모'),
        ),
    ]
