# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0077_marketyoutubevideo_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='날짜')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '투자일기',
                'verbose_name_plural': '투자일기',
                'db_table': 'market_diary',
                'ordering': ['-date'],
            },
        ),
    ]
