# Generated by Django 5.2.8

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0078_marketdiary'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='stocks.info', verbose_name='종목')),
            ],
            options={
                'verbose_name': '종목 투자일지',
                'verbose_name_plural': '종목 투자일지',
                'db_table': 'stock_diary',
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
