# Generated by Django 5.2.8

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0084_alter_info_interest_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='날짜')),
                ('date_text', models.CharField(help_text='정확한 날짜 또는 대략적 시기 (예: 4월 말경, 2분기 중)', max_length=50, verbose_name='날짜 텍스트')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(blank=True, default='', verbose_name='내용')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='stocks.info', verbose_name='종목')),
            ],
            options={
                'verbose_name': '종목 이벤트',
                'verbose_name_plural': '종목 이벤트',
                'db_table': 'stock_event',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
