# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0085_stock_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockevent',
            name='order',
            field=models.IntegerField(default=0, verbose_name='정렬순서'),
        ),
        migrations.AlterModelOptions(
            name='stockevent',
            options={'ordering': ['order', '-created_at'], 'verbose_name': '종목 이벤트', 'verbose_name_plural': '종목 이벤트'},
        ),
    ]
