# Generated by Django 5.2.8

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0086_stockevent_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='stocks.customsector', verbose_name='섹터')),
            ],
            options={
                'verbose_name': '섹터 투자일지',
                'verbose_name_plural': '섹터 투자일지',
                'db_table': 'sector_diary',
                'ordering': ['-date'],
                'unique_together': {('sector', 'date')},
            },
        ),
    ]
