# Generated by Django 5.2.8

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0088_customsector_trade_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='날짜')),
                ('date_text', models.CharField(max_length=50, verbose_name='날짜 텍스트')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(blank=True, default='', verbose_name='내용')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='stocks.customsector', verbose_name='섹터')),
            ],
            options={
                'verbose_name': '섹터 이벤트',
                'verbose_name_plural': '섹터 이벤트',
                'db_table': 'sector_event',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
