# Generated by Django 5.2.8 on 2026-04-12 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0089_sector_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoetf',
            name='buy_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='매수가'),
        ),
        migrations.AddField(
            model_name='infoetf',
            name='buy_reason',
            field=models.TextField(blank=True, default='', verbose_name='매수근거'),
        ),
        migrations.AddField(
            model_name='infoetf',
            name='memo',
            field=models.TextField(blank=True, default='', verbose_name='메모'),
        ),
        migrations.AddField(
            model_name='infoetf',
            name='memo_updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='메모 수정일'),
        ),
        migrations.AddField(
            model_name='infoetf',
            name='sell_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='매도가'),
        ),
        migrations.AddField(
            model_name='infoetf',
            name='sell_reason',
            field=models.TextField(blank=True, default='', verbose_name='매도근거'),
        ),
        migrations.AddField(
            model_name='infoetf',
            name='trade_updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='매매근거 수정일'),
        ),
        migrations.CreateModel(
            name='ETFEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='날짜')),
                ('date_text', models.CharField(max_length=50, verbose_name='날짜 텍스트')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(blank=True, default='', verbose_name='내용')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='stocks.infoetf', verbose_name='ETF')),
            ],
            options={
                'verbose_name': 'ETF 이벤트',
                'verbose_name_plural': 'ETF 이벤트',
                'db_table': 'etf_event',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ETFDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='stocks.infoetf', verbose_name='ETF')),
            ],
            options={
                'verbose_name': 'ETF 투자일지',
                'verbose_name_plural': 'ETF 투자일지',
                'db_table': 'etf_diary',
                'ordering': ['-date'],
                'unique_together': {('etf', 'date')},
            },
        ),
    ]
