# Generated by Django 5.2.8 on 2026-04-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0090_infoetf_buy_price_infoetf_buy_reason_infoetf_memo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectoryoutubevideo',
            name='note',
            field=models.CharField(blank=True, help_text='간단한 요약 메모', max_length=300, verbose_name='한줄 메모'),
        ),
    ]
