# Generated by Django 5.2.8 on 2026-04-13 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0091_sectoryoutubevideo_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, verbose_name='연도')),
                ('quarter', models.CharField(blank=True, db_index=True, help_text='1Q, 2Q, 3Q, 4Q - null이면 연간', max_length=2, null=True, verbose_name='분기')),
                ('is_estimated', models.BooleanField(default=False, verbose_name='추정치여부')),
                ('revenue', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='매출액')),
                ('cost_of_revenue', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='매출원가')),
                ('gross_profit', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='매출총이익')),
                ('sga_expense', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='판매비와관리비')),
                ('operating_profit', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='영업이익')),
                ('pretax_income', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='법인세비용차감전계속사업이익')),
                ('net_income', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='당기순이익')),
                ('eps', models.IntegerField(blank=True, help_text='(지배주주지분)주당순이익', null=True, verbose_name='주당순이익')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.info', verbose_name='종목')),
            ],
            options={
                'verbose_name': '포괄손익계산서',
                'verbose_name_plural': '포괄손익계산서',
                'db_table': 'income_statement',
                'ordering': ['-year', '-quarter'],
                'unique_together': {('stock', 'year', 'quarter')},
            },
        ),
    ]
