# Generated by Django 5.2.8 on 2026-04-14 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0092_add_income_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, verbose_name='연도')),
                ('quarter', models.CharField(blank=True, db_index=True, help_text='1Q, 2Q, 3Q, 4Q - null이면 연간', max_length=2, null=True, verbose_name='분기')),
                ('is_estimated', models.BooleanField(default=False, verbose_name='추정치여부')),
                ('total_assets', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='자산총계')),
                ('cash', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='현금및현금성자산')),
                ('receivables', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='매출채권및기타채권')),
                ('tangible_assets', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='유형자산')),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='부채총계')),
                ('short_term_debt', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='단기차입금')),
                ('long_term_debt', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='장기차입금')),
                ('total_equity', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='자본총계')),
                ('retained_earnings', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='이익잉여금')),
                ('interest_bearing_debt', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='이자발생부채')),
                ('net_debt', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='순부채')),
                ('capex', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='CAPEX')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.info', verbose_name='종목')),
            ],
            options={
                'verbose_name': '재무상태표',
                'verbose_name_plural': '재무상태표',
                'db_table': 'balance_sheet',
                'ordering': ['-year', '-quarter'],
                'unique_together': {('stock', 'year', 'quarter')},
            },
        ),
    ]
