# Generated by Django 5.2.8 on 2026-04-14 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0093_add_balance_sheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, verbose_name='연도')),
                ('quarter', models.CharField(blank=True, db_index=True, help_text='1Q, 2Q, 3Q, 4Q - null이면 연간', max_length=2, null=True, verbose_name='분기')),
                ('is_estimated', models.BooleanField(default=False, verbose_name='추정치여부')),
                ('operating_cash_flow', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='영업활동으로인한현금흐름')),
                ('net_income', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='당기순이익')),
                ('working_capital_change', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='영업활동으로인한자산부채변동(운전자본변동)')),
                ('interest_paid', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='이자지급(-)')),
                ('tax_paid', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='법인세납부(-)')),
                ('investing_cash_flow', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='투자활동으로인한현금흐름')),
                ('financing_cash_flow', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='재무활동으로인한현금흐름')),
                ('dividends_paid', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='배당금지급(-)')),
                ('cash_change', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='현금및현금성자산의증가')),
                ('ending_cash', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='기말현금및현금성자산')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.info', verbose_name='종목')),
            ],
            options={
                'verbose_name': '현금흐름표',
                'verbose_name_plural': '현금흐름표',
                'db_table': 'cash_flow',
                'ordering': ['-year', '-quarter'],
                'unique_together': {('stock', 'year', 'quarter')},
            },
        ),
    ]
