# Generated by Django 5.2.8 on 2026-04-14 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0094_add_cash_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitabilityRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, verbose_name='연도')),
                ('quarter', models.CharField(blank=True, db_index=True, max_length=2, null=True, verbose_name='분기')),
                ('is_estimated', models.BooleanField(default=False, verbose_name='추정치여부')),
                ('debt_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='부채비율')),
                ('net_debt_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='순부채비율')),
                ('current_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='유동비율')),
                ('interest_coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='이자보상배율')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.info', verbose_name='종목')),
            ],
            options={
                'verbose_name': '수익성',
                'verbose_name_plural': '수익성',
                'db_table': 'profitability_ratio',
                'ordering': ['-year', '-quarter'],
                'unique_together': {('stock', 'year', 'quarter')},
            },
        ),
    ]
