# Generated by Django 5.2.8 on 2026-04-14 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0095_add_profitability_ratio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfitabilityRatio',
            new_name='StabilityRatio',
        ),
        migrations.AlterModelOptions(
            name='stabilityratio',
            options={'ordering': ['-year', '-quarter'], 'verbose_name': '안정성', 'verbose_name_plural': '안정성'},
        ),
        migrations.AlterModelTable(
            name='stabilityratio',
            table='stability_ratio',
        ),
    ]
