# Generated by Django 5.2.8 on 2026-04-14 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0097_add_profitability_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, verbose_name='연도')),
                ('quarter', models.CharField(blank=True, db_index=True, max_length=2, null=True, verbose_name='분기')),
                ('is_estimated', models.BooleanField(default=False, verbose_name='추정치여부')),
                ('revenue_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='매출액증가율')),
                ('operating_profit_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='영업이익증가율')),
                ('net_income_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='순이익증가율')),
                ('equity_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='자기자본증가율')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.info', verbose_name='종목')),
            ],
            options={
                'verbose_name': '성장성',
                'verbose_name_plural': '성장성',
                'db_table': 'growth_ratio',
                'ordering': ['-year', '-quarter'],
                'unique_together': {('stock', 'year', 'quarter')},
            },
        ),
    ]
