# Generated by Django 5.2.8 on 2026-04-14 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0098_add_growth_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consensus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, verbose_name='연도')),
                ('is_estimated', models.BooleanField(default=False, verbose_name='추정치여부')),
                ('revenue', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='매출액')),
                ('yoy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='YoY')),
                ('operating_profit', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='영업이익')),
                ('net_income', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, verbose_name='당기순이익')),
                ('eps', models.IntegerField(blank=True, null=True, verbose_name='EPS')),
                ('bps', models.IntegerField(blank=True, null=True, verbose_name='BPS')),
                ('per', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PER')),
                ('pbr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PBR')),
                ('roe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ROE')),
                ('ev_ebitda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='EV/EBITDA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.info', verbose_name='종목')),
            ],
            options={
                'verbose_name': '컨센서스',
                'verbose_name_plural': '컨센서스',
                'db_table': 'consensus',
                'ordering': ['-year'],
                'unique_together': {('stock', 'year')},
            },
        ),
    ]
