# Generated by Django 5.2.8 on 2026-04-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0099_add_consensus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consensus',
            options={'ordering': ['-year', '-quarter'], 'verbose_name': '컨센서스', 'verbose_name_plural': '컨센서스'},
        ),
        migrations.AlterUniqueTogether(
            name='consensus',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='consensus',
            name='quarter',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True, verbose_name='분기'),
        ),
        migrations.AlterUniqueTogether(
            name='consensus',
            unique_together={('stock', 'year', 'quarter')},
        ),
    ]
