# Generated by Django 5.2.8 on 2026-04-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0100_add_consensus_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='consensus_analysis',
            field=models.TextField(blank=True, default='', help_text='컨센서스분석 내용 (마크다운)', verbose_name='컨센서스분석'),
        ),
        migrations.AddField(
            model_name='info',
            name='consensus_analysis_updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='컨센서스분석 업데이트일'),
        ),
        migrations.AddField(
            model_name='info',
            name='financial_analysis_v2',
            field=models.TextField(blank=True, default='', help_text='기업분석 탭 재무분석 (마크다운)', verbose_name='재무분석(v2)'),
        ),
        migrations.AddField(
            model_name='info',
            name='financial_analysis_v2_updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='재무분석(v2) 업데이트일'),
        ),
        migrations.AddField(
            model_name='info',
            name='quarter_analysis',
            field=models.TextField(blank=True, default='', help_text='직전분기재무해석 내용 (마크다운)', verbose_name='직전분기재무해석'),
        ),
        migrations.AddField(
            model_name='info',
            name='quarter_analysis_updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='직전분기재무해석 업데이트일'),
        ),
    ]
