# Generated by Django 5.2.8 on 2026-04-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0101_add_analysis_fields_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='consensus_analysis_previous',
            field=models.TextField(blank=True, default='', help_text='직전 컨센서스분석 내용 (자동 보관)', verbose_name='컨센서스분석 직전'),
        ),
        migrations.AddField(
            model_name='info',
            name='financial_analysis_v2_previous',
            field=models.TextField(blank=True, default='', help_text='직전 재무분석 내용 (자동 보관)', verbose_name='재무분석(v2) 직전'),
        ),
    ]
