# Generated by Django 5.2.8 on 2026-04-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0102_add_previous_analysis_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='consensus_analysis_previous_updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='컨센서스분석 직전 업데이트일'),
        ),
        migrations.AddField(
            model_name='info',
            name='financial_analysis_v2_previous_updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='재무분석(v2) 직전 업데이트일'),
        ),
    ]
