# Generated by Django 5.2.8 on 2026-04-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0103_add_previous_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='consensus_analysis_base_quarter',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='컨센서스분석 기준분기'),
        ),
        migrations.AddField(
            model_name='info',
            name='consensus_analysis_previous_base_quarter',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='컨센서스분석 직전 기준분기'),
        ),
        migrations.AddField(
            model_name='info',
            name='financial_analysis_v2_base_quarter',
            field=models.CharField(blank=True, default='', help_text='예: 2025/4Q', max_length=10, verbose_name='재무분석(v2) 기준분기'),
        ),
        migrations.AddField(
            model_name='info',
            name='financial_analysis_v2_previous_base_quarter',
            field=models.CharField(blank=True, default='', help_text='예: 2025/3Q', max_length=10, verbose_name='재무분석(v2) 직전 기준분기'),
        ),
    ]
