# Generated by Django 5.2.8 on 2026-04-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0114_add_recent_trade_judgment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(help_text='업종 소분류 이름 (최대 100자)', max_length=100, verbose_name='소분류명'),
        ),
    ]
