# Generated by Django 5.2.8 on 2026-05-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0123_add_waiting_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockquestionreport',
            name='ai_question',
            field=models.TextField(blank=True, default='', help_text='실제 AI에게 한 질문 원문', verbose_name='AI질문'),
        ),
        migrations.AddField(
            model_name='stockquestionreport',
            name='is_tracking',
            field=models.BooleanField(default=False, help_text='계속 업데이트할 질문 여부', verbose_name='트래킹'),
        ),
    ]
