# Generated by Django 5.2.8 on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0124_stockquestionreport_ai_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='avg_buy_price',
            field=models.IntegerField(blank=True, help_text='실제 매입 평균단가 (손익 계산용, 매매근거의 목표 매수가와 별개)', null=True, verbose_name='평단가'),
        ),
    ]
