# Generated by Django 5.2.8 on 2026-05-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0125_info_avg_buy_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorquestionreport',
            name='ai_question',
            field=models.TextField(blank=True, default='', help_text='실제 AI에게 한 질문 원문', verbose_name='AI질문'),
        ),
        migrations.AddField(
            model_name='sectorquestionreport',
            name='is_tracking',
            field=models.BooleanField(default=False, help_text='계속 업데이트할 질문 여부', verbose_name='트래킹'),
        ),
        migrations.AddField(
            model_name='sectorquestionreport',
            name='my_opinion',
            field=models.TextField(blank=True, default='', help_text='이 리서치에 대한 나의 의견 (텍스트)', verbose_name='내생각'),
        ),
    ]
