# Generated by Django 5.2.8 on 2026-06-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0126_sectorquestionreport_ai_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAccountSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='YYYYMMDD (API: dt)', unique=True, verbose_name='일자')),
                ('total_buy_amount', models.BigIntegerField(blank=True, help_text='단위: 원 (API: tot_buy_amt)', null=True, verbose_name='총 매입가')),
                ('total_eval_amount', models.BigIntegerField(blank=True, help_text='단위: 원 (API: tot_evlt_amt)', null=True, verbose_name='총 평가금액')),
                ('total_eval_profit', models.BigIntegerField(blank=True, help_text='단위: 원 (API: tot_evltv_prft)', null=True, verbose_name='총 평가손익')),
                ('profit_rate', models.DecimalField(blank=True, decimal_places=2, help_text='단위: % (API: tot_prft_rt)', max_digits=10, null=True, verbose_name='수익률')),
                ('deposit_balance', models.BigIntegerField(blank=True, help_text='단위: 원 (API: dbst_bal)', null=True, verbose_name='예수금')),
                ('estimated_asset', models.BigIntegerField(blank=True, help_text='단위: 원 (API: day_stk_asst)', null=True, verbose_name='추정자산')),
                ('cash_weight', models.DecimalField(blank=True, decimal_places=2, help_text='단위: % (API: buy_wght)', max_digits=6, null=True, verbose_name='현금비중')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '계좌 일별 스냅샷',
                'verbose_name_plural': '계좌 일별 스냅샷',
                'db_table': 'daily_account_snapshot',
                'ordering': ['-date'],
            },
        ),
    ]
