# Generated by Django 5.2.8 on 2026-06-03 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0127_dailyaccountsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stk_cd', models.CharField(help_text='API: stk_cd', max_length=10, unique=True, verbose_name='종목코드')),
                ('stk_nm', models.CharField(help_text='API: stk_nm', max_length=100, verbose_name='종목명')),
                ('rmnd_qty', models.IntegerField(blank=True, help_text='단위: 1주 (API: rmnd_qty)', null=True, verbose_name='보유수량')),
                ('buy_uv', models.IntegerField(blank=True, help_text='단위: 원 (API: buy_uv)', null=True, verbose_name='매입단가')),
                ('cur_prc', models.IntegerField(blank=True, help_text='단위: 원 (API: cur_prc)', null=True, verbose_name='현재가')),
                ('eval_amount', models.BigIntegerField(blank=True, help_text='단위: 원 (API: evlt_amt)', null=True, verbose_name='평가금액')),
                ('eval_profit', models.BigIntegerField(blank=True, help_text='단위: 원 (API: evltv_prft)', null=True, verbose_name='평가손익')),
                ('profit_rate', models.DecimalField(blank=True, decimal_places=2, help_text='단위: % (API: prft_rt)', max_digits=10, null=True, verbose_name='수익률')),
                ('eval_weight', models.DecimalField(blank=True, decimal_places=2, help_text='단위: % (API: evlt_wght)', max_digits=6, null=True, verbose_name='평가비중')),
                ('buy_weight', models.DecimalField(blank=True, decimal_places=2, help_text='단위: % (API: buy_wght)', max_digits=6, null=True, verbose_name='매수비중')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('info', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holding_record', to='stocks.info', verbose_name='연동 종목')),
                ('info_etf', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holding_record', to='stocks.infoetf', verbose_name='연동 ETF')),
            ],
            options={
                'verbose_name': '보유 종목',
                'verbose_name_plural': '보유 종목',
                'db_table': 'holding',
                'ordering': ['-eval_weight'],
            },
        ),
    ]
