# Generated by Django 5.2.8 on 2026-06-03 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0128_holding'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTradeDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='YYYYMMDD (요청 base_dt)', unique=True, verbose_name='일자')),
                ('total_sell_amount', models.BigIntegerField(blank=True, help_text='단위: 원 (API: tot_sell_amt)', null=True, verbose_name='총매도금액')),
                ('total_buy_amount', models.BigIntegerField(blank=True, help_text='단위: 원 (API: tot_buy_amt)', null=True, verbose_name='총매수금액')),
                ('total_commission_tax', models.BigIntegerField(blank=True, help_text='단위: 원 (API: tot_cmsn_tax)', null=True, verbose_name='총수수료/세금')),
                ('total_settlement_amount', models.BigIntegerField(blank=True, help_text='단위: 원 (API: tot_exct_amt)', null=True, verbose_name='총정산금액')),
                ('total_pl_amount', models.BigIntegerField(blank=True, help_text='단위: 원 (API: tot_pl_amt)', null=True, verbose_name='총손익금액')),
                ('profit_rate', models.DecimalField(blank=True, decimal_places=2, help_text='단위: % (API: tot_prft_rt)', max_digits=10, null=True, verbose_name='총수익률')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '매매일지 일별 요약',
                'verbose_name_plural': '매매일지 일별 요약',
                'db_table': 'daily_trade_diary',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stk_cd', models.CharField(help_text='API: stk_cd', max_length=10, verbose_name='종목코드')),
                ('stk_nm', models.CharField(help_text='API: stk_nm', max_length=100, verbose_name='종목명')),
                ('buy_avg_price', models.IntegerField(blank=True, help_text='단위: 원 (API: buy_avg_pric)', null=True, verbose_name='매수평균가')),
                ('buy_qty', models.IntegerField(blank=True, help_text='단위: 1주 (API: buy_qty)', null=True, verbose_name='매수수량')),
                ('buy_amount', models.BigIntegerField(blank=True, help_text='단위: 원 (API: buy_amt)', null=True, verbose_name='매수금액')),
                ('sell_avg_price', models.IntegerField(blank=True, help_text='단위: 원 (API: sel_avg_pric)', null=True, verbose_name='매도평균가')),
                ('sell_qty', models.IntegerField(blank=True, help_text='단위: 1주 (API: sell_qty)', null=True, verbose_name='매도수량')),
                ('sell_amount', models.BigIntegerField(blank=True, help_text='단위: 원 (API: sell_amt)', null=True, verbose_name='매도금액')),
                ('commission_tax', models.IntegerField(blank=True, help_text='단위: 원 (API: cmsn_alm_tax)', null=True, verbose_name='수수료/세금')),
                ('pl_amount', models.BigIntegerField(blank=True, help_text='단위: 원 (API: pl_amt)', null=True, verbose_name='손익금액')),
                ('profit_rate', models.DecimalField(blank=True, decimal_places=2, help_text='단위: % (API: prft_rt)', max_digits=10, null=True, verbose_name='수익률')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('info', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_record', to='stocks.info', verbose_name='연동 종목')),
                ('info_etf', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_record', to='stocks.infoetf', verbose_name='연동 ETF')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='stocks.dailytradediary', verbose_name='매매일지')),
            ],
            options={
                'verbose_name': '매매일지 종목별 내역',
                'verbose_name_plural': '매매일지 종목별 내역',
                'db_table': 'daily_trade',
                'ordering': ['-diary__date', 'stk_cd'],
                'unique_together': {('diary', 'stk_cd')},
            },
        ),
    ]
