# Generated by Django 5.2.8 on 2026-06-04 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0129_dailytradediary_dailytrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsector',
            name='buy_reason',
        ),
        migrations.RemoveField(
            model_name='customsector',
            name='sell_reason',
        ),
        migrations.RemoveField(
            model_name='customsector',
            name='trade_updated_at',
        ),
        migrations.RemoveField(
            model_name='info',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='info',
            name='buy_price_range',
        ),
        migrations.RemoveField(
            model_name='info',
            name='buy_reason',
        ),
        migrations.RemoveField(
            model_name='info',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='info',
            name='sell_reason',
        ),
        migrations.RemoveField(
            model_name='info',
            name='trade_updated_at',
        ),
        migrations.RemoveField(
            model_name='infoetf',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='infoetf',
            name='buy_reason',
        ),
        migrations.RemoveField(
            model_name='infoetf',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='infoetf',
            name='sell_reason',
        ),
        migrations.RemoveField(
            model_name='infoetf',
            name='trade_updated_at',
        ),
    ]
