# Generated by Django 5.2.8 on 2026-06-04 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0130_remove_trade_basis_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdiary',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': '종목 투자일지', 'verbose_name_plural': '종목 투자일지'},
        ),
        migrations.AlterUniqueTogether(
            name='stockdiary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='entry_confidence',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='진입 확신도'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='entry_emotion',
            field=models.CharField(blank=True, choices=[('calm', '차분'), ('rush', '조급'), ('fomo', 'FOMO'), ('overconfident', '확신과다')], default='', max_length=15, verbose_name='진입 시 심리'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='entry_reason',
            field=models.TextField(blank=True, default='', verbose_name='진입 근거'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='entry_validity',
            field=models.CharField(blank=True, choices=[('correct', '맞았음'), ('wrong', '틀렸음'), ('lucky', '운(과정틀림·결과좋음)')], default='', max_length=10, verbose_name='진입 근거 유효성'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='exit_emotion',
            field=models.CharField(blank=True, choices=[('calm', '차분'), ('fear', '공포'), ('regret', '미련'), ('relief', '안도')], default='', max_length=15, verbose_name='매도 시 심리'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='invalidation_condition',
            field=models.TextField(blank=True, default='', verbose_name='무효화 조건'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='is_planned',
            field=models.BooleanField(default=True, verbose_name='계획매매 여부'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='lesson',
            field=models.TextField(blank=True, default='', verbose_name='한 줄 교훈'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='plan_compliance',
            field=models.CharField(blank=True, choices=[('planned', '계획대로'), ('chased', '추격매수함'), ('averaged', '물타기함'), ('early_exit', '조기이탈')], default='', max_length=15, verbose_name='계획 대비 행동'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='planned_stop_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='계획 손절가'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='position_size',
            field=models.CharField(blank=True, choices=[('planned', '계획대로'), ('over', '과도하게 실음'), ('under', '적게 실음')], default='', max_length=10, verbose_name='비중(계획 대비)'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='process_evaluation',
            field=models.CharField(blank=True, choices=[('good', '잘한 매매'), ('bad', '못한 매매')], default='', max_length=5, verbose_name='과정 평가'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='sell_reason_type',
            field=models.CharField(blank=True, choices=[('target', '목표달성'), ('stop', '룰대로손절'), ('invalidated', '무효화조건충족'), ('time_stop', '시간손절'), ('panic', '공포·뇌동'), ('early_profit', '조기익절')], default='', max_length=15, verbose_name='매도 사유'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='setup_type',
            field=models.CharField(blank=True, choices=[('pullback', '정배열눌림목'), ('breakout', '돌파'), ('bounce', '낙폭과대반등'), ('event', '이벤트베팅'), ('impulse', '뇌동(계획없음)')], default='', max_length=20, verbose_name='셋업 유형'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='stop_compliance',
            field=models.CharField(blank=True, choices=[('kept', '지킴'), ('delayed', '미룸'), ('na', '해당없음')], default='', max_length=10, verbose_name='손절 준수 여부'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='target_price_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='1차 목표가'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='trade',
            field=models.OneToOneField(blank=True, help_text='DailyTrade 자동 연결 (매수/매도 수량·가격·손익)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_diary', to='stocks.dailytrade', verbose_name='매매 데이터'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='trade_type',
            field=models.CharField(choices=[('buy', '매수'), ('sell', '매도')], default='buy', max_length=4, verbose_name='매매 구분'),
        ),
        migrations.RemoveField(
            model_name='stockdiary',
            name='content',
        ),
        migrations.RemoveField(
            model_name='stockdiary',
            name='is_buy',
        ),
        migrations.RemoveField(
            model_name='stockdiary',
            name='is_sell',
        ),
    ]
