# Generated by Django 5.2.8 on 2026-08-14 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0131_redesign_stock_diary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='.env APPKEY_<KEY> / token_<key>.json 에 쓰임 (예: main, sub1)', max_length=20, unique=True, verbose_name='계좌 키')),
                ('name', models.CharField(help_text='화면 탭에 표시될 이름', max_length=50, verbose_name='계좌명')),
                ('is_primary', models.BooleanField(default=False, help_text='종목 상세 보유 현황·투자일지가 바라보는 계좌 (1개만 지정)', verbose_name='주계좌')),
                ('is_active', models.BooleanField(default=True, help_text='해제하면 수집·화면 표시에서 제외', verbose_name='활성')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '계좌',
                'verbose_name_plural': '계좌',
                'db_table': 'account',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='dailyaccountsnapshot',
            name='date',
            field=models.DateField(help_text='YYYYMMDD (API: dt)', verbose_name='일자'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='stk_cd',
            field=models.CharField(help_text='API: stk_cd', max_length=10, verbose_name='종목코드'),
        ),
        migrations.AddField(
            model_name='dailyaccountsnapshot',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='stocks.account', verbose_name='계좌'),
        ),
        migrations.AddField(
            model_name='holding',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='stocks.account', verbose_name='계좌'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyaccountsnapshot',
            unique_together={('account', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together={('account', 'stk_cd')},
        ),
    ]
