# Generated by Django 5.2.8 on 2026-08-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0135_add_sub_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(db_index=True, help_text='KOSPI, KOSDAQ', max_length=10, verbose_name='시장')),
                ('date', models.DateField(db_index=True, verbose_name='일자')),
                ('close', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='종가')),
                ('ma20', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='20일 이동평균')),
                ('disparity', models.DecimalField(blank=True, decimal_places=2, help_text='종가 / 20일 이동평균 * 100', max_digits=7, null=True, verbose_name='이격도(20일)')),
                ('adr', models.DecimalField(blank=True, decimal_places=2, help_text='등락비율, 단위: % (출처: adrinfo.kr)', max_digits=7, null=True, verbose_name='ADR')),
                ('foreign_net_20d', models.BigIntegerField(blank=True, help_text='단위: 백만원 (MarketTrend 최근 20영업일 합)', null=True, verbose_name='외국인 20일 누적 순매수')),
                ('ma200', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='200일 이동평균')),
                ('ma200_gap', models.DecimalField(blank=True, decimal_places=2, help_text='(종가 / 200일 이동평균 - 1) * 100, 단위: %', max_digits=7, null=True, verbose_name='200일선 대비')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '시장지표',
                'verbose_name_plural': '시장지표',
                'db_table': 'market_indicator',
                'ordering': ['-date', 'market'],
                'indexes': [models.Index(fields=['market', '-date'], name='market_indi_market_bac755_idx'), models.Index(fields=['-date'], name='market_indi_date_ffd0ae_idx')],
                'unique_together': {('market', 'date')},
            },
        ),
    ]
