# Generated by Django 5.2.8 on 2026-08-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0136_marketindicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketindicator',
            name='foreign_net_20d_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='최근 250거래일의 20일 누적값 중 오늘 값의 위치 (0~100)', max_digits=5, null=True, verbose_name='외국인 20일 누적 백분위'),
        ),
        migrations.AddField(
            model_name='marketindicator',
            name='ma200_gap_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='최근 250거래일의 200일선 대비 값 중 오늘 값의 위치 (0~100)', max_digits=5, null=True, verbose_name='200일선 대비 백분위'),
        ),
    ]
