# Generated by Django 5.2.8 on 2026-08-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0137_marketindicator_foreign_net_20d_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketindicator',
            name='disparity_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='최근 250거래일의 이격도 중 오늘 값의 위치 (0~100)', max_digits=5, null=True, verbose_name='이격도 백분위'),
        ),
    ]
