# Generated by Django 5.2.8 on 2026-08-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0138_marketindicator_disparity_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(db_index=True, help_text='KOSPI, KOSDAQ', max_length=10, verbose_name='시장')),
                ('date', models.DateField(db_index=True, help_text='판단의 근거가 된 지표 날짜 (저장일이 아니다)', verbose_name='지표 기준일')),
                ('headline', models.CharField(blank=True, help_text='접힌 상태에서 보여주는 요약', max_length=300, verbose_name='한 줄 결론')),
                ('stance', models.CharField(blank=True, choices=[('공격적', '공격적'), ('보통', '보통'), ('신중', '신중'), ('관망', '관망')], max_length=10, verbose_name='매매 스탠스')),
                ('content', models.TextField(verbose_name='답변 전문')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='저장일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '시장 AI 판단',
                'verbose_name_plural': '시장 AI 판단',
                'db_table': 'market_analysis',
                'ordering': ['-date', 'market'],
                'indexes': [models.Index(fields=['market', '-date'], name='market_anal_market_0d5172_idx')],
                'unique_together': {('market', 'date')},
            },
        ),
    ]
