# Generated by Django 5.2.8 on 2026-08-17 10:40

from django.db import migrations, models


def merge_super_into_normal(apps, schema_editor):
    """초관심을 관심으로 합친다. 그 자리는 '보유'가 대신하며 자산에서 파생된다."""
    Info = apps.get_model('stocks', 'Info')
    moved = Info.objects.filter(interest_level='super').update(interest_level='normal')
    print(f'  초관심 -> 관심 {moved}건')


def split_back(apps, schema_editor):
    """되돌릴 수 없다 — 어느 것이 초관심이었는지 기록이 남지 않는다."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0139_marketanalysis'),
    ]

    operations = [
        migrations.RunPython(merge_super_into_normal, split_back),
        migrations.AlterField(
            model_name='info',
            name='interest_level',
            field=models.CharField(blank=True, choices=[('normal', '관심'), ('waiting', '대기')], help_text='내가 고르는 단계 (관심 > 대기). 보유는 여기 없다 — 자산에서 파생되며 화면에서 관심/대기보다 앞선다.', max_length=10, null=True, verbose_name='관심단계'),
        ),
    ]
