# Generated by Django 5.2.8 on 2026-08-17 10:46

from django.db import migrations, models


def register_existing_as_interest(apps, schema_editor):
    """
    지금 등록된 ETF 는 전부 손으로 골라 넣은 것들이다 — 곧 '관심'이다.
    (is_active 는 원래 '목록에 보일 것'이라는 뜻으로 쓰였다)
    """
    InfoETF = apps.get_model('stocks', 'InfoETF')
    n = InfoETF.objects.filter(is_active=True).update(interest_level='normal')
    print(f'  등록 ETF {n}개 -> 관심')


def clear_interest(apps, schema_editor):
    InfoETF = apps.get_model('stocks', 'InfoETF')
    InfoETF.objects.update(interest_level=None)


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0140_interest_level_merge_super'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoetf',
            name='interest_level',
            field=models.CharField(blank=True, choices=[('normal', '관심'), ('waiting', '대기')], max_length=10, null=True, verbose_name='관심단계'),
        ),
        migrations.RunPython(register_existing_as_interest, clear_interest),
    ]
