# Generated by Django 5.2.8 on 2026-08-18 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0142_fix_overflow_decimals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, help_text='원문 주소. 링크 없이 내용만 적어도 된다.', max_length=1000, verbose_name='링크')),
                ('content', models.TextField(help_text='AI 요약을 붙여넣는 자리. 첫 줄이 목록의 제목이 된다.', verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='저장일시')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='stocks.info', verbose_name='종목')),
            ],
            options={
                'verbose_name': '자료',
                'verbose_name_plural': '자료',
                'db_table': 'material',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ExcludedYoutubeChannel',
        ),
        migrations.RemoveField(
            model_name='news',
            name='stock',
        ),
        migrations.DeleteModel(
            name='PreferredYoutubeChannel',
        ),
        migrations.AlterUniqueTogether(
            name='youtubevideo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='stock',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='YoutubeVideo',
        ),
    ]
