# Generated by Django 5.2.8 on 2026-08-18 23:31

from django.db import migrations, models


def carry_over(apps, schema_editor):
    """
    시장 AI 판단을 새 표로 옮긴다.

    market_analysis 는 시장 전용이었다. 같은 방식(날짜별 덮어쓰기)을 리포트·
    수급·공시에서도 쓰게 되어 kind/key 를 가진 한 표로 합친다. 이미 저장해둔
    판단은 지우지 않고 kind='market' 으로 넘긴다.
    """
    old = apps.get_model('stocks', 'MarketAnalysis')
    new = apps.get_model('stocks', 'AiNote')
    rows = [
        new(kind='market', key=row.market, date=row.date,
            headline=row.headline, stance=row.stance, content=row.content)
        for row in old.objects.all()
    ]
    if rows:
        new.objects.bulk_create(rows)
    print(f'  시장 AI 판단 {len(rows)}건 이관')


def noop(apps, schema_editor):
    """되돌릴 수 없다 — 옮긴 뒤 옛 표를 지운다."""



class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0143_drop_news_youtube_add_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('market', '시황'), ('report', '리포트'), ('supply', '수급'), ('gongsi', '공시')], help_text='어느 화면의 판단인지', max_length=20, verbose_name='자리')),
                ('key', models.CharField(help_text='KOSPI/KOSDAQ 또는 종목코드', max_length=20, verbose_name='대상')),
                ('date', models.DateField(help_text='판단의 근거가 된 데이터 날짜 (저장일이 아니다)', verbose_name='기준일')),
                ('headline', models.CharField(blank=True, help_text='접힌 상태에서 보여주는 요약', max_length=300, verbose_name='한 줄 결론')),
                ('stance', models.CharField(blank=True, choices=[('공격적', '공격적'), ('보통', '보통'), ('신중', '신중'), ('관망', '관망')], max_length=10, verbose_name='매매 스탠스')),
                ('content', models.TextField(verbose_name='답변 전문')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='저장일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': 'AI 판단',
                'verbose_name_plural': 'AI 판단',
                'db_table': 'ai_note',
                'ordering': ['-date', 'kind', 'key'],
            },
        ),
        # 표를 지우기 전에 옮긴다
        migrations.RunPython(carry_over, noop),
        migrations.DeleteModel(
            name='MarketAnalysis',
        ),
        migrations.AddIndex(
            model_name='ainote',
            index=models.Index(fields=['kind', 'key', '-date'], name='ai_note_kind_f1326d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ainote',
            unique_together={('kind', 'key', 'date')},
        ),
    ]
