# Generated by Django 5.2.8 on 2026-08-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0150_drop_research_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorquestionreport',
            name='report_type',
            field=models.CharField(choices=[('html', 'HTML'), ('markdown', '마크다운')], default='markdown', help_text='리포트의 형식 (HTML 또는 마크다운)', max_length=10, verbose_name='리포트 형식'),
        ),
        migrations.AlterField(
            model_name='stockquestionreport',
            name='report_type',
            field=models.CharField(choices=[('html', 'HTML'), ('markdown', '마크다운')], default='markdown', help_text='리포트의 형식 (HTML 또는 마크다운)', max_length=10, verbose_name='리포트 형식'),
        ),
    ]
