# Generated by Django 5.2.8 on 2026-10-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0158_etf_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='interest_level',
            field=models.CharField(blank=True, choices=[('normal', '관심'), ('waiting', '대기'), ('shared', '공유')], help_text='내가 고르는 단계 (관심 > 대기). 보유는 여기 없다 — 자산에서 파생되며 화면에서 관심/대기보다 앞선다. 공유는 로그인 없이 보는 /ontoo/ 페이지에 올라간다.', max_length=10, null=True, verbose_name='관심단계'),
        ),
    ]
