# Generated by Django 5.2.8 on 2026-10-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0159_alter_info_interest_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='로그인 없이 여럿이 보는 /ontoo/ 페이지에 올릴 종목 여부. 관심·대기와 같이 켤 수 있다.', verbose_name='공유'),
        ),
        migrations.AlterField(
            model_name='info',
            name='interest_level',
            field=models.CharField(blank=True, choices=[('normal', '관심'), ('waiting', '대기')], help_text='내가 고르는 단계 (관심 > 대기). 둘 중 하나만 고른다. 보유는 여기 없다 — 자산에서 파생되며 화면에서 관심/대기보다 앞선다. 공유는 단계가 아니라 깃발이다 (is_shared).', max_length=10, null=True, verbose_name='관심단계'),
        ),
    ]
