# Generated by Django 5.2.8 on 2026-10-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0160_info_is_shared_alter_info_interest_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='shared_memo',
            field=models.TextField(blank=True, default='', help_text='OnToo(/ontoo/)에 보여줄 메모. 내 메모와 따로 저장된다.', verbose_name='공유 메모'),
        ),
        migrations.AddField(
            model_name='info',
            name='shared_memo_updated_at',
            field=models.DateField(blank=True, help_text='공유 메모 마지막 수정일', null=True, verbose_name='공유 메모 업데이트일'),
        ),
    ]
